### ISSUE TITLE
Dark Elements (icons, logs) are invisible in black and dark styles

### ISSUE THREAD

**Issue by chromer030** [MatsuriDayo/nekoray#10]
![Screenshot_20220606_172502](https://user-images.githubusercontent.com/13361552/172165827-0cbd8d20-f9a6-4390-9105-64148d90ff99.jpg)

**Comment by arm64v8a** [comment]
actually it's not ready for dark mode

**Comment by arm64v8a** [comment]
top bar icons changed in 0.6
now it looks better in dark styles

**Comment by chromer030** [comment]
@arm64v8a 
New icons are great but the logs is invisible yet in dark styles :
![Screenshot_20220612_134528](https://user-images.githubusercontent.com/13361552/173226330-f8eb5017-a214-4037-924b-c9f9bd7fe591.jpg)
