### ISSUE TITLE
win7 X64 无法定位程序输入点 CreateDXGIFactory2 与动态链接库 dxgi.dll

### ISSUE THREAD

**Issue by ybmgq** [MatsuriDayo/nekoray#1002]
## 描述问题
win7 X64 无法定位程序输入点 CreateDXGIFactory2 与动态链接库 dxgi.dll
预期行为：
win7 X64 无法定位程序输入点 CreateDXGIFactory2 与动态链接库 dxgi.dll
实际行为：
win7 X64 无法定位程序输入点 CreateDXGIFactory2 与动态链接库 dxgi.dll
## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by zcyle** [comment]
请求支持win7系统..谢谢
