### ISSUE TITLE
error: ubuntu22.04 Run ./Launcher and ./nekoray error

### ISSUE THREAD

**Issue by FlRiver** [MatsuriDayo/nekoray#1006]
./launcher ->
2023/11/02 23:52:58 exe: launcher exe dir: /home/nekoray
2023/11/02 23:52:58 Running as launcher
2023/11/02 23:52:58 LD_LIBRARY_PATH=/home/nekoray/usr/lib QT_PLUGIN_PATH=/home/nekoray/usr/plugins ./nekoray
./nekoray: error while loading shared libraries: libpcre2-16.so.0: cannot open shared object file: No such file or directory

./nekoray ->
./nekoray: error while loading shared libraries: libQt5Network.so.5: cannot open shared object file: No such file or directory

The question is to install the QT5 included library on your own？But I found the link library in the file.

**Comment by Misaka-blog** [comment]
On ubuntu, use deb package for install
