### ISSUE TITLE
custom configuration Load Balancing not work correctly!!

### ISSUE THREAD

**Issue by rexi1r** [MatsuriDayo/nekoray#101]
**描述问题**
Hi, I want to use a custom config to add other servers as a load balancer according to this description:
https://guide.v2fly.org/en_US/app/balance.html#load-balancing

I used something like this:
```
"vnext": [
        {
            "address": "**.***.***.***",
            "port": 80,
            "users": [
                {
                    "encryption": "none",
                    "id": "3fa9asdf7af2-b5f7-4f25-asdfa15d-4fdf89ec5asdfdd2"
                }
            ]
        },
        {
            "address": "***.***.***.***",
            "port": 80,
            "users": [
                {
                    "encryption": "none",
                    "id": "3fa9asdf7af2-basdf5f7-4f25-a15sdfd-4fdfasdf89ec5dd2"
                }
            ]
        }]
```

预期行为：
I expected to send traffic to those servers and act like a load balancer

实际行为：

**如何复现**
I figured it just uses address and port and my vnext custom config is not affected.

提供有帮助的截图，录像，文字说明，订阅链接等。

**日志**

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

![1](https://user-images.githubusercontent.com/4881902/197626416-1821e1e1-848d-4297-96c2-caf142598e76.png)
![2](https://user-images.githubusercontent.com/4881902/197626441-94affb65-3c2a-4721-a638-08ffc6c42ef9.png)

**Comment by rexi1r** [comment]
thanks, that worked perfectly

**Comment by papampi** [comment]
Can you please share a full config for 2 or more vmess load balance connections?
Whatever I do I can't make it work
