### ISSUE TITLE
BUG: vless的http/2的订阅链接，nekoray的singbox识别错误。

### ISSUE THREAD

**Issue by lih24338** [MatsuriDayo/nekoray#1012]
## 描述问题
vless的http/2的订阅链接，nekoray的singbox识别错误。
预期行为：
当导入vless的h2订阅链接时，Nekoray在sing-box核心下，会自动识别为http，并且可以正常选择和连接。
实际行为：
当导入vless的h2链接时，Nekoray报错如下:"LoadConfig return error outbound options: unknown transport type: h2"，并且编辑节点时，发现协议是tcp。
## 如何复现
寻找一个vless的传输协议是h2的链接，使用nekoray的sing-box核心，导入链接并尝试连接。

测试链接 vless://b26cf765-9cc9-418c-8051-5c432ae783ee@test.your.link:2008?security=reality&sni=cloudflare.com&fp=chrome&pbk=OFI_ni-YmIuob07rrsw6VP57Nqxmb2BKrn0fx6DIhmU&sid=7aa003cb3e4b5ac2&spx=/&type=h2&encryption=none#测试链接
## 日志

sing-box-extra: 1.6.rc1 NekoBox: nekoray-3.24-2023-10-28
2023/11/05 02:38:23 nekobox_core grpc server listening at 127.0.0.1:60652
导入了 0 个配置
导入了 1 个配置
>>>>>>>> 正在启动配置 [VLESS] 测试链接
<<<<<<<< 启动配置失败: [VLESS] 测试链接
2023/11/05 02:39:08 [Info] sing-box closed in 0 ms
>>>>>>>> 正在启动配置 [VLESS] 新干线英国伦敦
<<<<<<<< 启动配置失败: [VLESS] 新干线英国伦敦

**Comment by lih24338** [comment]
android上的NekoBox，是完全正常的。

**Comment by HowardZorn** [comment]
我发现，vmess协议也有类似问题。
