### ISSUE TITLE
BUG: does not respond to the function disable proxy mode

### ISSUE THREAD

**Issue by f1h0** [MatsuriDayo/nekoray#1017]
## Describe the problem

Expected behavior:

Actual behavior:

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

ver: 3.17

when you want to turn off nekoray
the proxy works and is not disabled.
You have to manually go into the browser settings and disable the proxy mode, it’s very inconvenient

**Comment by purofle** [comment]
The latest version of Nekoray cannot be replicated on Windows 11 23H2.
