### ISSUE TITLE
Feature Request: LAN proxy share

### ISSUE THREAD

**Issue by NeroBlackstone** [MatsuriDayo/nekoray#1018]
## Description suggestions
Allow LAN proxy sharing like cfw.
## Necessity of recommendations
Helpful for other devices can't install Nekoray.

**Comment by xiaorong61** [comment]
> 这个功能本来就有，点“程序”->“允许其他设备连接”，这时nekoray会监听0.0.0.0:2080混合端口，局域网其他机器可以访问这台机器的nekoray作为socks5或http代理

挺隐蔽的，我还在设置里面找
