### ISSUE TITLE
Add support for UDPGW

### ISSUE THREAD

**Issue by farhadsakhaei** [MatsuriDayo/nekoray#1020]
Hi,
Please add support for UDPGW (UDP GateWay) for SSH connections,
All other SSH apps (HTTP Custom, HTTP Injector, NetMod) supports UDPGW
Also there is this lack on Matsuri
Without UDPGW , the UDP doesn't work at all on SSH
This means all voice calls and video calls doesn't work when using NekoBox and Matsuri on SSH
You can find more info about this here:
https://github.com/powermx/badvpn/
I love Nekobox and Matsuri , Just lack of this feature is there 
Thank you

**Comment by farhadsakhaei** [comment]
@purofle 
I don't know why they closed this request:
https://github.com/SagerNet/sing-box/issues/1098

But I think this feature is not related to the SSH connector, Because UDPGW is another exe file which connects after connecting SSH connection
It's very simple to implement in the program

**Comment by deuteros-gex** [comment]
If you just want to nekoray to work simultaneously with badvpn, well, nekoray already does.
Proxies and vpns always work with each other if you watch out for the route table of your OS.
There is nothing nekoray can do since it is out of scope.

**Comment by farhadsakhaei** [comment]
@purofle  @deuteros-gex 
I just mentioned a thing which all other applications do this, I think it's really necessary for a SSH connector
You can check all these apps: HTTP CUSTOM, HTTP INJECTOR, NetMod
if you check all of these applications support UDPGW and you can find it's settings too

**Comment by deuteros-gex** [comment]
You keep on emphasizing that something needs to be done, but why ?
If the so-called udpgw feature can be achieved with the badvpn solution you mentioned, feel free to take advantage of it and nekoray can work simultaneously with it anyway.
There is no need for nekoray to implement anything.
