### ISSUE TITLE
BUG: can't open the client because of the dependency "libprotobuf".

### ISSUE THREAD

**Issue by Ambrose1ee** [MatsuriDayo/nekoray#1022]
## 描述问题

预期行为：
直接打开Nekoray

实际行为：
无法打开

## 如何复现
（现在libprotobuf.so.24已经升级为25）
终端输入nekoray: 
输出：error while loading shared libraries: libprotobuf.so.24: cannot open shared object file: No such file or directory

**Comment by purofle** [comment]
nekoray 是通过哪种方式安装的？

**Comment by KafCoppelia** [comment]
Archlinux AUR安装会有这个问题

**Comment by Ambrose1ee** [comment]
是的，aur：nekoray-git

**Comment by uzvg** [comment]
我从ArchLinuxCN安装的也有这个问题。

**Comment by purofle** [comment]
从 aur 重新安装 nekoray-git 即可解决
其实就是本地 libprotobuf 版本变了，需要重新编译
ArchlinuxCN 的版本请去给 ArchlinuxCN 开 issue
