### ISSUE TITLE
adding some more protocols and options like chain

### ISSUE THREAD

**Issue by Hiradpi** [MatsuriDayo/nekoray#1027]
can you please consider adding chain option like the one in nekobox that allows you to chain 2 defrent kind of configuration together 
and please consider adding ssh protocol and wireguard

**Comment by misagh72** [comment]
there is chainproxy in the app / and for ssh wireguard use singbox outbound configuration
![Untitled](https://github.com/MatsuriDayo/nekoray/assets/49818860/9132e472-1000-4111-979b-cd4e8d980482)

**Comment by Morrigan-Ship** [comment]
wireguard and ssh?
