### ISSUE TITLE
BUG: Nekoray用系统代理时，关机重开电脑，发现win11系统设置里面的代理设置还是打开的

### ISSUE THREAD

**Issue by KwpGitHub** [MatsuriDayo/nekoray#1031]
## 描述问题

预期行为：Nekoray用系统代理时，关机重开电脑，发现win11系统设置里面的代理设置应该关闭，关机处理应该跟手动退出Nekoray一样，要把电脑的代理设置关闭。

实际行为：Nekoray用系统代理时，关机重开电脑，发现win11系统设置里面的代理设置还是打开的。

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by 8884361** [comment]
这无论是哪一款代理GUI都是预期问题，因为系统通知软件关闭时，软件无法再设定系统代理设置
