### ISSUE TITLE
Reality

### ISSUE THREAD

**Issue by OghabTeam** [MatsuriDayo/nekoray#1045]
## Necessity of recommendations

WHY YOU DONT ADD Reality to windows app?!

**Comment by misagh72** [comment]
app already support Reality in long time

**Comment by yiqingdi** [comment]
![Snipaste_2023-11-18_08-09-35](https://github.com/MatsuriDayo/nekoray/assets/82999642/24a3be52-45f4-44b8-bf8f-b4a063c4d093)
