### ISSUE TITLE
希望像v2rayN一样，除了tun和代理模式外能增加一个pac的模式

### ISSUE THREAD

**Issue by KwpGitHub** [MatsuriDayo/nekoray#1051]
## Description suggestions
希望像v2rayN一样，除了tun和代理模式外能增加一个pac的模式
## Necessity of recommendations
因为有些网站和软件没有这个功能会出错，这个功能是必须的。

**Comment by purofle** [comment]
pac 模式即为路由分流，所以不会加入。
