### ISSUE TITLE
BUG: 系统代理模式下（软件未开启随系统启动），电脑关机重启后，系统代理还在，这样造成电脑上不了网！

### ISSUE THREAD

**Issue by alay2022** [MatsuriDayo/nekoray#1070]
## 描述问题

预期行为：软件在需要时启动，电脑关机重启后，系统代理取消

实际行为：系统代理仍然还在，导致上网显示  代理服务器拒绝。

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by purofle** [comment]
请先退出软件再关机/重启

**Comment by alay2022** [comment]
这个回复有点甩锅。谁关机/重启会先关闭这些个软件。


V2rayN就不存在这个问题，建议考虑下。




&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "purofle"; 
发送时间: 2023年11月27日(星期一) 上午8:57
收件人: "MatsuriDayo/nekoray"; 
抄送: "alay2022"; "Author"; 
主题: Re: [MatsuriDayo/nekoray] BUG: 系统代理模式下（软件未开启随系统启动），电脑关机重启后，系统代理还在，这样造成电脑上不了网！ (Issue #1070)

&nbsp;


 
请先退出软件再关机/重启
