### ISSUE TITLE
BUG：“服务器 > 分享 > 导出 sing-box 配置”导出的配置不可用

### ISSUE THREAD

**Issue by nukemiko** [MatsuriDayo/nekoray#1077]
## 描述问题

OS: Arch Linux
Nekoray version: 3.25-1
Sing-box version: 1.6.7

预期行为：通过标题所述方式导出的配置，在保存为文件后可以被 sing-box 使用

实际行为：通过标题所述方式导出的配置，在保存为文件后，sing-box 无法通过该配置文件启动，报错信息如下：

```sh-session
FATAL[0000] create service: parse route options: parse dns server[dns-local]: unknown DNS server format: underlying://0.0.0.0
```

## 如何复现

1. 在 NekoRay 主窗口里选择一个**可用的**节点，按照标题所述的方式复制生成的 sing-box 配置，并将其写入文件 `sing-box-config.json`
2. 运行命令 `<sing-box 命令或文件路径> run -c sing-box-config.json`。

**Comment by TrezorTop** [comment]
I encountered the same problem, if you managed to solve it, please write about it. We will share the solution if we succeed

我也遇到了同样的问题，如果你解决了，请写一下。 如果成功，我们将分享解决方案

**Comment by pangge4531** [comment]
我也同问？

**Comment by cornerot** [comment]
Replace "underlying://0.0.0.0" with "local"

**Comment by Nicolayka** [comment]
I have the same problem, but on Windows. Where can this be fixed? Thanks

**Comment by Nicolayka** [comment]
> Replace "underlying://0.0.0.0" with "local"


I have the same problem, but on Windows. Where can this be fixed? Thanks

**Comment by moyuwuhen601** [comment]
同样的问题，我升级后就出现了，我是windows系统

**Comment by d1monch1k** [comment]
Same problem

**Comment by cajgwy** [comment]
在根目录 点  当天跟新的nekobox.exe

**Comment by MikooooCode** [comment]
透過Everything把Nekoray刪除乾净后重新安裝可以解決
