### ISSUE TITLE
error: NO permission to write /opt/nekoray kubuntu 每次重启都是第一次使用内核,然后出现 NO permission to write /opt/nekoray

### ISSUE THREAD

**Issue by 839781960** [MatsuriDayo/nekoray#1092]
## Describe the problem
Provide helpful screenshots, videos, text descriptions, subscription links, etc.
![image](https://github.com/MatsuriDayo/nekoray/assets/114645865/3a715b42-f03b-47a9-80c1-c4658034a7a7)
![image](https://github.com/MatsuriDayo/nekoray/assets/114645865/f655c23f-ca3d-4534-b1ea-96bff737ee35)
No permission to write /opt/nekoray

**Comment by arisskz6** [comment]
on my M LInux, the same problem

**Comment by sserpenss** [comment]
Just change the owner for /opt/nekoray on yourself like:
`sudo chown -R your_user_name. /opt/nekoray `
