### ISSUE TITLE
Download traffic counter resets when reaches to 3 GB

### ISSUE THREAD

**Issue by chromer030** [MatsuriDayo/nekoray#11]
When traffic usages reaches to 3 GB and more , if we restart the nekogram the counter will be reset to 0 !
It seems that something in GUI is broken because the config is OK :

![Screenshot_20220606_224027](https://user-images.githubusercontent.com/13361552/172220730-44e9bd56-5f0b-4b60-93ea-62438ba7a705.jpg)

**Comment by arm64v8a** [comment]
0.4
