### ISSUE TITLE
[Linux] Vpn mode recovery after an unexpected exit

### ISSUE THREAD

**Issue by smaznet** [MatsuriDayo/nekoray#111]
some time when i close or kill nekoray
on next launch vpn mode is off but vpn mode is enabled somehow (i checked my ip)

and vpn mode checkbox cannot be  toggled
when i tested with -debug this error happend
`start service: initialize inbound/tun[0]: configure tun interface: device or resource busy`

**Comment by SafaSafari** [comment]
You can make PR my friend :)))))

**Comment by m0x31h0x64i** [comment]
same problem here, with nekoray latest version on windows 11, see the picture below:

**Comment by m0x31h0x64i** [comment]
I realized this problem is because after closing the program, the program will automatically restart. But how can this problem be solved?

**Comment by m0x31h0x64i** [comment]
reinstalling nekoray didn't help me

**Comment by m0x31h0x64i** [comment]
i tried older versions until 1.7 but no fix ... what is the problem can be from ?

**Comment by Akbar30Bill** [comment]
I have the same issue on mac using `sudo killall nekobox_core` did the trick and fixed it.

**Comment by meyroon** [comment]
> You can make PR my friend :)))))

سلام..
داخل نکوری proxy کار میده، vpn mode کار نمیده...
ارورر میده :
 https://8.8.8.8/dns-query: context deadline exceeded
کسی میتونه دست مهربانی به سویم دراز کنه ؟

**Comment by SafaSafari** [comment]
درود
please speak English :))
you can set 'remote dns' option to 8.8.8.8 and enable enhanced domain name resolution
go and check routing settings

**Comment by SafaSafari** [comment]
also, make sure your system time is correct

**Comment by meyroon** [comment]
![Capture](https://user-images.githubusercontent.com/120992142/208351898-6d657b29-f815-4454-a7e7-10523b567438.PNG)
hi, tnQ for your dametgarm :D :))
Still not working..
is there any other setting to change or check ??

**Comment by SafaSafari** [comment]
> ![Capture](https://user-images.githubusercontent.com/120992142/208351898-6d657b29-f815-4454-a7e7-10523b567438.PNG) hi, tnQ for your dametgarm :D :)) Still not working.. is there any other setting to change or check ??

Make sure شو ke time system okeye :))
Badesh ham as proxy correct use kon

**Comment by meyroon** [comment]
Hi mojadad..

new error is : 
LookupManyDoH: ************* 28 <nil> LookupManyDoH: all tries failed

************* : my v2ray server

as soos as i hit the VPN Mode checkbox, internet(wifi) sign in taskbar changes to no inteernet sign !! :D

God kheyret bede pls help me :D

**Comment by uncoxali** [comment]
سلام من هم به خوبی داشتم باهاش کار میکردم و یهو کلا دیگه قط شد و نتونستم vpn mode را فعال کنم چند باری حذف کردم و دوباره گرفتم 

ubuntu 20.04

**Comment by meyroon** [comment]
@uncoxali 
من برای کارِ دیگه ای دی ان اس رو ست کردم روی کلودفلر، بعدا دیدم اینم درست شده 😄 
اما بنظرم این راه درستی نیس ! نمیدونم والا 
اگر کسی مشکل رو پیدا کرد بگه لطفاً

I changed DNS for another purpose and used Cloudflare DNS. Later, I found out that the problem of not connecting to Nekuri VPN was solved.
I doubt that this is the right solution.
If anyone finds a solution, please post it here 👍 😉

**Comment by ANTISEC12** [comment]
@meyroon 

Doesn't work for me!

**Comment by uncoxali** [comment]
> @uncoxali من برای کارِ دیگه ای دی ان اس رو ست کردم روی کلودفلر، بعدا دیدم اینم درست شده smile اما بنظرم این راه درستی نیس ! نمیدونم والا اگر کسی مشکل رو پیدا کرد بگه لطفاً
> 
> I changed DNS for another purpose and used Cloudflare DNS. Later, I found out that the problem of not connecting to Nekuri VPN was solved. I doubt that this is the right solution. If anyone finds a solution, please post it here +1 wink

راهشو میگید ما هم  درست کنیم دمت گرم

**Comment by ANTISEC12** [comment]
> هعی سر ایشو من چه بحثی راهی انداختین
> 
> Hey in head of my issue what bahs is rah oftading...

خب همه این مشکل رو داریم! 
We all have this problem.

**Comment by ANTISEC12** [comment]
![2023-01-08_13-29](https://user-images.githubusercontent.com/32206857/211190086-278d57a8-ac87-4169-b81f-982d8ca6a696.png)


اگه آدرس دامنه ای داخل نکوری تنظیم کردید که بای‌پس بشه
حذفش کنید مشکل برطرف می‌شه.

**Comment by SafaSafari** [comment]
if nekoray closed unexpectedly, enter this command on terminal and try to run nekoray VPN mode again
`sudo ip link delete nekoray-tun`

**Comment by pedramtehrani** [comment]
Hi
I have an issue on my M1 Mac that's not work my internet after i disconnecting Nekoray, Chrome show me error to check my proxy setting but it's OK. 

PLz Help me

**Comment by banxter** [comment]
First, close nekoray, then, find "nekoray_core.exe" in task manager and close it..
it solved my problem..

**Comment by AmirEbrahimHashemiDot** [comment]
دوستان من nekory رو نصب کردم ترافیک همه ی سیستم از اون رد میشه جز ترمینال
کسی راهی داره؟ (ubuntu 22.04)
I installed Nekuri, the traffic of all the system passes through it, except the terminal
Does anyone have a way?

**Comment by Akbar30Bill** [comment]
> دوستان من nekory رو نصب کردم ترافیک همه ی سیستم از اون رد میشه جز ترمینال کسی راهی داره؟ (ubuntu 22.04) I installed Nekuri, the traffic of all the system passes through it, except the terminal Does anyone have a way?
```
export SOCKS5_PROXY=http://127.0.0.1:<Nekoray port>
export HTTPS_PROXY=http://127.0.0.1:<Nekoray port>
export HTTP_PROXY=http://127.0.0.1:<Nekoray port>
```

**Comment by mrmoein** [comment]
##  **this work for me**

![Screenshot 2023-02-16 021150](https://user-images.githubusercontent.com/48438999/219205274-46f4e21d-b2f0-4942-9cb6-33f5bf738d40.png)
![Screenshot 2023-02-16 021213](https://user-images.githubusercontent.com/48438999/219205168-265b04d3-fb4b-48c5-becf-cfcae9b5f539.png)
![Screenshot 2023-02-16 021100](https://user-images.githubusercontent.com/48438999/219205269-43304362-935d-46be-bd8f-9450ffe55bd7.png)

**Comment by AmirEbrahimHashemiDot** [comment]
Thank you for your response :)

**Comment by amin273** [comment]
Hey everybody, I was wondering how I can fix this error:
[Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context deadline exceeded
سلام و وقت بخیر دوستان، کسی میدونه این خطا رو چحوری میتونم رفع کنم؟ ممنون میشم راهنماییم کنید: 
![Capture](https://user-images.githubusercontent.com/126659320/222096519-fd1b82d1-76f7-4a49-857c-c5eddcf7ae77.JPG)

**Comment by S-STALWART-S** [comment]
downgrade to version 2.14, use vpn mode for all apps except browsers, use proxy mode for browsers

**Comment by niazaslani** [comment]
Hey
I cannot enable tun or vpn mode in nekoray 3.19 since today 9/1/2023. When I enable it, it disables itself suddenly and automatically.
I appreciate

**Comment by MajidMohammadian** [comment]
بچه ها من ورژن 2.28 رو نصب کردم و مشکلی نداشت، من هم مثل شما ها ورژن آخر رو گرفته بودم و مشکل داشتم باهاش
دهنش سرویس ۲ ساعت وقتم رو گرفت

**Comment by soheilous** [comment]
I also had problems with the latest version (3.26) on my `MX Linux`. Currently using 3.21, no issues or anything
