### ISSUE TITLE
can not open nekoray in windows 7 64 bit

### ISSUE THREAD

**Issue by Soheil777** [MatsuriDayo/nekoray#1131]
hi when i want open software i see this error
i install everything it may need
![neko](https://github.com/MatsuriDayo/nekoray/assets/29523286/1341026e-40c8-4339-b4e2-c2bc1f68e807)
![neko1](https://github.com/MatsuriDayo/nekoray/assets/29523286/29df5a67-8789-418f-b56e-eb1cbde5900a)

**Comment by Soheil777** [comment]
what can i do? please help me

**Comment by mbkh66** [comment]
Hi Soheil
 pls use the Version 3.17  > Windows. 7.

the Nekoray is no longer support windows 7.
