### ISSUE TITLE
[BUG] Long confirm msg problem

### ISSUE THREAD

**Issue by APT-ZERO** [MatsuriDayo/nekoray#115]
![image](https://user-images.githubusercontent.com/41063376/199040613-2d848199-b476-4ad1-88a5-5ec0b363afba.png)

When deleting duplicates servers or removing unavailable servers, Nekoray shows list of all servers that will be erased for confirmation
it's OK, but when list is too long, process not responds for seconds and then can no more see Yes / No buttons because list is too long, buttons will be out of screen

**Comment by miladmeidanshahi** [comment]
is it fixed?
