### ISSUE TITLE
DEAD PROJECT?

### ISSUE THREAD

**Issue by CrazyDigital** [MatsuriDayo/nekoray#1156]
i realized @arm64v8a has been inactive and no update was made for 1 month

**Comment by misagh72** [comment]
Did you know he or she have real life?

**Comment by CrazyDigital** [comment]
i wonder where he/she is captured by CCP

**Comment by purofle** [comment]
> i wonder where he/she has been captured by CCP

No, It’s just that I don’t want to maintain it for the time being.
