### ISSUE TITLE
BUG: 没有直连国内站点

### ISSUE THREAD

**Issue by pasawu** [MatsuriDayo/nekoray#1157]
## 描述问题

预期行为：
国内网站走直连

实际行为：
国内网站没有走直连

## 如何复现

![image](https://github.com/MatsuriDayo/nekoray/assets/40690686/ec42a095-7760-4b22-a887-d68deebbe870)

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by Eyion** [comment]
实现科学上网是必须启用系统代理吗，我只开tun好像不可以打开外网。另外，不论是单开tun，还是同时开了前面2个，下面流量都显示走的代理。如果要实现分流，要如何设置？

**Comment by pasawu** [comment]
> 出站改为bypass，默认就是直连，只需要填代理的网站即可

> 出站改为bypass，默认就是直连，只需要填代理的网站即可

按你说的方式解决了，谢谢！
