### ISSUE TITLE
Add wireproxy.

### ISSUE THREAD

**Issue by Noir16** [MatsuriDayo/nekoray#1171]
## Description suggestions
https://github.com/pufferffish/wireproxy/
A wireguard client that exposes itself as a socks5/http proxy or tunnels.

## Necessity of recommendations
Can relay the wireguard server to SOCKS5 instead of the VPN. There is no GUI tool for this, so I think it would be a nice addition.

**Comment by siq0o** [comment]
both sing-box and the xray cores support wireguard.

**Comment by siq0o** [comment]
> @siq0o This is not an additional suggestion for Wireguard 'VPN'. An additional suggestion for software that tunnels the Wireguard VPN to a 'SOCKS5 proxy'.

both xray core and sing-box support wireguard outbound / socks5 inbound. see:
https://xtls.github.io/en/config/
https://sing-box.sagernet.org/configuration/

**Comment by Noir16** [comment]
@siq0o This is a tool to outbound socks5 with wireguard inbound, not socks5 inbound.
Do I understand the tool correctly for now? As far as I know, the tool does not currently inbound wireguard.
I referenced https://github.com/MatsuriDayo/nekoray/issues/1009, but it's a key-related issue, which is difficult to configure on some commercial VPNs.

**Comment by siq0o** [comment]
> @siq0o This is a tool to outbound socks5 with wireguard inbound, not socks5 inbound. Do I understand the tool correctly for now? As far as I know, the tool does not currently inbound wireguard. I referenced #1009, but it's a key-related issue, which is difficult to configure on some commercial VPNs.

both cores can do the same as wireproxy, but there's no way to add a wireguard connection with gui, so you need to manually write a custom outbound config. if you're requesting a GUI option, it's a duplicate of the same #1009 you mentioned.

**Comment by Noir16** [comment]
I recently tried again:
`failed to send data packets: write udp [ip] -> [ip]: wsasend: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.`

Unlike wireproxy, they seem to require more configuration or are unreachable due to implementation limitations.

**Comment by siq0o** [comment]
> I recently tried again: `failed to send data packets: write udp [ip] -> [ip]: wsasend: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.`
> 
> Unlike wireproxy, they seem to require more configuration or are unreachable due to implementation limitations.

Use [this](https://sing-box.sagernet.org/configuration/outbound/wireguard/) template. New profile > custom (sing-box outbound)
By default nekoray listens on port 2080.

**Comment by Noir16** [comment]
> Use this template. New profile > custom (sing-box outbound)

@siq0o That template didn't work. (unsupported outbound)

**Comment by Noir16** [comment]
I modified it as follows:
The Mixed Listen Port is set to 4080.
```
{
  "type": "wireguard",
  "tag": "wireguard-out",
  "server": "127.0.0.1",
  "server_port": 4080,
  "system_interface": false,
  "interface_name": "JP-FREE#120005",
  "local_address": [
    "10.2.0.2/32"
  ],
  "private_key": "IPwA5EtN/V0YF2dwKiCSyvSCMBOweQvpxjH1YNFifkw=",
  "peers": [
    {
      "server": "138.199.21.206",
      "server_port": 51820,
      "public_key": "6vLkUgiS/K8p5dTMwUQo6tiyJ65DrM8E2mwO+QFz/zs=",
      "allowed_ips": [
        "0.0.0.0/1",
        "128.0.0.0/1"
      ],
      "reserved": [0, 0, 0]
    }
  ],
  "peer_public_key": "6vLkUgiS/K8p5dTMwUQo6tiyJ65DrM8E2mwO+QFz/zs=",
  "reserved": [0, 0, 0],
  "workers": 4,
  "mtu": 1280,
  "network": "tcp"
}
```

The original wireguard config looks like this:
```
[Interface]
PrivateKey = IPwA5EtN/V0YF2dwKiCSyvSCMBOweQvpxjH1YNFifkw=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
PublicKey = 6vLkUgiS/K8p5dTMwUQo6tiyJ65DrM8E2mwO+QFz/zs=
AllowedIPs = 0.0.0.0/1, 128.0.0.0/1
Endpoint = 138.199.21.206:51820
```

**Comment by siq0o** [comment]
Here is your **outbound** config:
```
{
    "local_address": [
        "10.2.0.2/32"
    ],
    "mtu": 1280,
    "peer_public_key": "6vLkUgiS/K8p5dTMwUQo6tiyJ65DrM8E2mwO+QFz/zs=",
    "private_key": "IPwA5EtN/V0YF2dwKiCSyvSCMBOweQvpxjH1YNFifkw=",
    "server": "138.199.21.206",
    "server_port": 51820,
    "type": "wireguard"
}
```
You can change the listen port in gui. (preferences -> basic settings)
If you want to view your full sing-box config, you cant right click on your config -> share -> export sing-box config. you can use that config with sing-box directly (if you don't want to use nekoray)

**Comment by Noir16** [comment]
@siq0o You can change the listen port in gui. (preferences -> basic settings)

That's not the point right now, the point is that that config example doesn't work in any case due to a structural issue with UDP packet transport. I think it's better to wait for support than to try to fix this.

**Comment by siq0o** [comment]
@Noir16 your configuration was incorrect and i provided you one. sing-box supports wireguard and i use it on a daily basis. feel free to read the documentations.

**Comment by Noir16** [comment]
@siq0o 
> ```
> {
>     "local_address": [
>         "10.2.0.2/32"
>     ],
>     "mtu": 1280,
>     "peer_public_key": "6vLkUgiS/K8p5dTMwUQo6tiyJ65DrM8E2mwO+QFz/zs=",
>     "private_key": "IPwA5EtN/V0YF2dwKiCSyvSCMBOweQvpxjH1YNFifkw=",
>     "server": "138.199.21.206",
>     "server_port": 51820,
>     "type": "wireguard"
> }
> ```

> I recently tried again: `failed to send data packets: write udp [ip] -> [ip]: wsasend: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.`

Same error

**Comment by siq0o** [comment]
> The original wireguard config looks like this:
> 
> ```
> [Interface]
> PrivateKey = IPwA5EtN/V0YF2dwKiCSyvSCMBOweQvpxjH1YNFifkw=
> Address = 10.2.0.2/32
> DNS = 10.2.0.1
> 
> [Peer]
> PublicKey = 6vLkUgiS/K8p5dTMwUQo6tiyJ65DrM8E2mwO+QFz/zs=
> AllowedIPs = 0.0.0.0/1, 128.0.0.0/1
> Endpoint = 138.199.21.206:51820
> ```
are you able to connect using other clients (such as wireproxy)? If the answer is yes, there must be some configuration error somewhere.

**Comment by Noir16** [comment]
I decided to just use Wireproxy in CLI form with cmd and vbs files.
