### ISSUE TITLE
怎么查看“绕过局域网和大陆”的基础上添加的网址直接连接而不是走代理？

### ISSUE THREAD

**Issue by redstoneleo** [MatsuriDayo/nekoray#1202]
我在“路由设置 - 预设 - 绕过局域网和大陆”的基础上添加了如下网址希望直接连接而不是走代理，请问我该怎么查看实际上是否有效果呢？刚从v2rayN转过来，不太清楚情况，希望多多指教，谢谢！

![image](https://github.com/MatsuriDayo/nekoray/assets/5896180/bbe1fd82-25ba-4b6d-8559-eaea01980cd6)

**Comment by redstoneleo** [comment]
@realcirno 看不懂，比如下面这个微信网址是不是走了代理？
![image](https://github.com/MatsuriDayo/nekoray/assets/5896180/9ac7789c-f41f-4096-8ed3-c39e89039ddf)

**Comment by redstoneleo** [comment]
怎么我的日志格式和你的不一样？你是怎么看到的？

**Comment by feedfor** [comment]
> @realcirno 看不懂，比如下面这个微信网址是不是走了代理？ ![image](https://private-user-images.githubusercontent.com/5896180/308407077-9ac7789c-f41f-4096-8ed3-c39e89039ddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTMxMzIsIm5iZiI6MTcwOTIxMjgzMiwicGF0aCI6Ii81ODk2MTgwLzMwODQwNzA3Ny05YWM3Nzg5Yy1mNDFmLTQwOTYtOGVkMy1jMzllODkwMzlkZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMTMyMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTgyZmUzZjhlNmNhMjhjNTE1ZGEzZjk4OTBlN2ViNWVhZjcyMmFhZDg4NzdkMTY2Zjk4ZDI2YjAyY2UwNGZhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-SA6rM7HT3Qt8pTc1l8qpuXBDdomgyBmyn2GQzmQNs8)

outbound 那个就是出，bypass对应的就是直连

**Comment by Morris-Lucifer** [comment]
> @UncleVitamin 谢谢指教！之前缺少了`domain:`并且末尾也多加了`,` @feedfor 确实是跟使用的核心不同有关系，之前用的singbox

你好，请问你知道怎么查看直连设置是否生效了吗？我的日志格式也是你这样的，设置了直连但是看到ui右下角只有代理有上下行流量，加了domain:，末尾没有逗号。并且当我关闭系统代理能访问大陆网站，打开就不行。
