### ISSUE TITLE
BUG: 使用sing-box内核的网络不可用

### ISSUE THREAD

**Issue by lyj404** [MatsuriDayo/nekoray#1230]
## 问题描述
我在使用sing-box内核进行上网的时候，选择的节点无法进行科学上网，但当我把内核切换成xray的时候，同样的节点却能进行科学上网，该节点的协议类型是Trojan，我查过sing-box支持的协议包括了Trojan协议
**这是使用xray内核的情况：**
[![network.png](https://s21.ax1x.com/2024/03/13/pFc1xT1.md.png)](https://imgse.com/i/pFc1xT1)
**同样的节点，但是使用sing-box内核的情况：**
[![not_network.png](https://s21.ax1x.com/2024/03/13/pFc1Ly4.md.png)](https://imgse.com/i/pFc1Ly4)

**使用的系统：Windows10 21H2**
**nekoray版本：3.26**

**Comment by vmnet** [comment]
把多路复用关掉，试下

**Comment by lyj404** [comment]
> 把多路复用关掉，试下
多路复用没看到关闭按钮啊
![Snipaste_2024-03-17_10-01-16](https://github.com/MatsuriDayo/nekoray/assets/74247293/300f7c7a-8c8a-43e3-9dfd-7a2378799e0b)

**Comment by lyj404** [comment]
> @lyj404 由于不知道你的Trojan订阅连接是否使用ws或grpc，所以没有办法确认实际不兼容的情况是什么，因为xray与sing-box处理ws及grpc参数有些不一样的配置要求，这个差异和Trojan协议没有任何关系，但订阅连接不可能照顾这些
> 
> 如果你自己对上述的配置差异有研究，那么可以手动调整到能用为止，如果不想折腾，xray内核能用就选xray
