### ISSUE TITLE
BUG: 更新Arch后nekoray 启动失败

### ISSUE THREAD

**Issue by yinzsw** [MatsuriDayo/nekoray#1240]
## 描述问题

```shell
nekoray
nekoray: error while loading shared libraries: libabsl_log_internal_check_op.so.2308.0.0: cannot open shared object file: No such file or directory
```

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by enk-it** [comment]
Looks like it is the same problem as in here 
https://github.com/Alexays/Waybar/issues/3059

**Comment by yinzsw** [comment]
好像是这次更新`abseil-cpp-20240116.1-1`导致的

**Comment by BanHammerYKT** [comment]
same problem

**Comment by yinzsw** [comment]
> same problem
> 
> update:
> 
> > abseil-cpp-20240116.1-1
> 
> downgrading to previous abseil-cpp-**20230802.1-1** cause problems with other apps and additional 🤦‍♂️
> 
> ```
> nekoray: error while loading shared libraries: libabsl_die_if_null.so.2401.0.0: cannot open shared object file: No such file or directory
> ```

我发现将`nekoray`切换为[nekoray-bin](https://aur.archlinux.org/packages/nekoray-bin)就没有这个问题了,可以用来临时解决一下

**Comment by the-nexi** [comment]
I also would like to report same issue:
` nekoray: error while loading shared libraries: libabsl_log_internal_check_op.so.2308.0.0: cannot open shared object file: No such file or directory `

For now, I've downgraded my system to temporary resolve this.

**Comment by the-nexi** [comment]
> See [archlinuxcn/repo#3708 (comment)](https://github.com/archlinuxcn/repo/issues/3708#issuecomment-2014408220) Are you using Unofficial ArchLinux packages repo such as Manjaro repo or CachyOS repo? Just run `sudo pacman -Syu extra/abseil-cpp`

I have been using nekoray from chaotic-aur, switching to nekoray-git have resolved the problem. I probably should notify chaotic-aur mantainers about the issue.
