### ISSUE TITLE
BUG: Hysteria 节点开启Tun模式无法联网

### ISSUE THREAD

**Issue by sunlewuyou** [MatsuriDayo/nekoray#1248]
## 描述问题

预期行为：
Hysteria 节点开启Tun模式可以正常代理

实际行为：
Hysteria 节点开启Tun模式不可以正常代理

## 如何复现

使用 Naive 节点开启Tun模式可以正常代理，使用 Hysteria节点则报错，日志截图如下。

## 日志

![image](https://github.com/MatsuriDayo/nekoray/assets/19728435/0a3104f2-7765-4db9-b3e8-d3c77b003e69)

**Comment by Initsnow** [comment]
@arm64v8a pre版本使用端口跳跃必须用到hysteria核心，而恰好这核心无法使用TUN模式，感觉这issue不该这样草率关闭
