### ISSUE TITLE
BUG: 连接电信手机热点无法联网

### ISSUE THREAD

**Issue by SakiTomato822** [MatsuriDayo/nekoray#1257]
## 描述问题

预期行为：通过节点正常访问互联网。

实际行为：连接任意（不限手机型号/系统）使用中国电信网络的手机热点后，Nekoray无法解析流量，各类测试均失败。

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。
https://drive.google.com/file/d/1_FQBxd5L66rUhlIRU_W54JEW2BRM-XrH/view?usp=sharing

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。
[neko - Copy.log](https://github.com/MatsuriDayo/nekoray/files/14835884/neko.-.Copy.log)

Nekoray出现了连接电信手机热点无法联网的情况，切换到移动热点立刻恢复正常，与https://github.com/MatsuriDayo/nekoray/issues/1239 类似，但不同的是，像issue中提供的“修改MTU”，为任意值均不起作用。
（手机网络正常，同节点使用Clash Verge系统代理可正常联网。）😭

**Comment by HeinousAgenda38** [comment]
修改国内运营商的dns试试，有泄漏但是比用不了强
