### ISSUE TITLE
配置简单路由, 支持通配符吗? 

### ISSUE THREAD

**Issue by sllzwsgdsg** [MatsuriDayo/nekoray#1287]
## 描述建议
我在公司使用软件的时候, 无法绕过公司原有的域名, 期望直连公司自己的域名
在配置简单路由时, 想要单独对某个域名进行配置, 
比如, 现在有如下域名需要配置为直连
test1.abc.com
test2.abc.com
video.abc.com
....
xxx.abc,com

期望能直接在直连一栏配置 *.abc.com就可以生效, 如果每一个域名都单独配置, 太麻烦了, 请问支持这种功能吗? 

![image](https://github.com/MatsuriDayo/nekoray/assets/8305759/ce765117-ebf9-4a78-ba95-bb3a52ff5c76)

## 建议的必要性
如果同个域名, 有多个主机名, 配置起来很麻烦, 需要每一个都配置上

**Comment by sllzwsgdsg** [comment]
我研究明白了. 做一个记录吧
用regexp关键字,后面跟正则来匹配域名的规则. 

regexp:^.*\.abc\.com$

**Comment by ZoidbergPi** [comment]
非常感谢
