### ISSUE TITLE
BUG: 如何在访问国内网站时不走流量 访问国外网站时用流量 例如访问b站时https://www.bilibili.com/不用流量

### ISSUE THREAD

**Issue by hibiki222** [MatsuriDayo/nekoray#1290]
## 描述问题

预期行为：

实际行为：

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by loskyertt** [comment]
你使用前都不看教程的啊？
