### ISSUE TITLE
BUG: 将代理停止以后，就打不开网页了

### ISSUE THREAD

**Issue by ghost-him** [MatsuriDayo/nekoray#1293]
## 描述问题

预期行为：

将代理关闭以后，电脑依然可以打开网页

实际行为：

将代理关闭以后，电脑无法打开网页

## 如何复现

启动一个代理后再将其关闭即可。

我也尝试过将系统代理与tun都关闭后再关闭软件，但是还是无效。也尝试了重启系统，重启networkmanager，都没用。ping 百度是可以ping通的，使用curl来连接百度也是可以的，但是使用chrome就是无法访问：

```
ghost-him@archlinux ~> curl -I https://www.baidu.com
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: keep-alive
Content-Length: 277
Content-Type: text/html
Date: Tue, 21 May 2024 04:44:00 GMT
Etag: "575e1f60-115"
Last-Modified: Mon, 13 Jun 2016 02:50:08 GMT
Pragma: no-cache
Server: bfe/1.0.8.18

```

## 日志

使用的系统是arch linux，使用pacman 安装的nekoray。

**Comment by swysgh** [comment]
有没有试过直接在系统设置里关闭系统代理

**Comment by ghost-him** [comment]
刚才试了一下，已经成功连上网了，没想到还可以这样做，谢谢！ @swysgh
