### ISSUE TITLE
请问如何在ubuntu22.04LTS使用nekoray 

### ISSUE THREAD

**Issue by AuRevoirzzz** [MatsuriDayo/nekoray#1319]
按照运行教程，我安装了`sudo apt install libxcb-xinerama0`但是还是无法运行nekoray，无论是双击或者是终端启动。
终端输入`./launcher`报错：
`2024/06/12 09:51:42 exe: launcher exe dir: /home/aurevoir/tools/nekoray-3.26-2023-12-09-linux64/nekoray
2024/06/12 09:51:42 Running as launcher
2024/06/12 09:51:42 LD_LIBRARY_PATH=/home/aurevoir/tools/nekoray-3.26-2023-12-09-linux64/nekoray/usr/lib QT_PLUGIN_PATH=/home/aurevoir/tools/nekoray-3.26-2023-12-09-linux64/nekoray/usr/plugins ./nekoray`
输入`./nakoray`报错：
`./nekoray: error while loading shared libraries: libQt5Network.so.5: cannot open shared object file: No such file or directory`
目前使用的窗口系统是wayland，我看教程是需要换成xcb桌面系统，但是在中文网络中搜索了一下，没有更换为xcb桌面系统教程。我对linux系统完全是小白，只是有软件不得不在linux系统运行，还请麻烦知道的大佬回答一下！非常感谢！

**Comment by Hydrogen93** [comment]
可能是要装包
sudo apt install  libqt5network5
