### ISSUE TITLE
BUG: 完全新装 运行报这个错误

### ISSUE THREAD

**Issue by hedsbj** [MatsuriDayo/nekoray#1328]
QApplication::regClass: Registering window class 'Qt652ScreenChangeObserverWindow' failed. (类已存在。)

**Comment by fyhzc** [comment]
me too

**Comment by AreChen** [comment]
同样的错误

**Comment by Leao9203** [comment]
same

**Comment by xz00311** [comment]
me too

**Comment by super302** [comment]
+1
我是导入一些节点后出现这个弹窗报错，然后程序再也打不开了，每次打开都出这个类似cmd窗口的命令行报错。

**Comment by ShadowSocksM** [comment]
me too
