### ISSUE TITLE
BUG: 4.0-beta2 和 4.0-beta1 都会报缺少 dll 文件

### ISSUE THREAD

**Issue by fscarmen** [MatsuriDayo/nekoray#1338]
## 描述问题

win11 运行时报错，缺少文件
![image](https://github.com/MatsuriDayo/nekoray/assets/62703343/1af4695a-1bfd-4f75-951a-bbcf3a0b632b)

我试了下载并安装以下运行库都好像不成功，而且容量大，麻烦

https://download.visualstudio.microsoft.com/download/pr/76e5dbb2-6ae3-4629-9a84-527f8feb709c/09002599b32d5d01dc3aa5dcdffcc984/windowsdesktop-runtime-8.0.6-win-x64.exe

## 解决方案
我根据报错的文件，逐一下载到 nekoray 目录，就可以正常运行了。不知道其他网友有没有一样的问题，我想把这些文件打包进去解压目录可能更好。

[5个dll 文件的压缩包， dll.zip](https://github.com/user-attachments/files/16107867/dll.zip)

**Comment by super302** [comment]
你这是系统缺少对应的VC运行库，不是软件的问题。
Microsoft Visual C++ Redistributable：包括多个版本，如 2008、2010、2012、2013、2017、2019 等。

**Comment by LightGrass** [comment]
安装完整的微软VC库就行。

**Comment by fscarmen** [comment]
我 google了也知道是这个意思，我也安装过，那很大的，下载和安装，好几百MB。只是想表达如果压缩包加上这几个文件，不但不会让用户麻烦安装 vc 运行库，同时几个文件也是 1MB 即可。我想“杀鸡焉用牛刀”也是这个道理。[原义是杀鸡怎能用宰牛的刀（鸡：比喻微不足道的小事情，小事物。 焉：疑问代词，怎能。 牛刀：比喻有强大功能，能力大的人或物）。 比喻做小事不必动用大的气力。]

**Comment by fscarmen** [comment]
其实问题我也是解决的了。只是提提我认为"合理化的建议"。
