### ISSUE TITLE
[Solution] SSL handshake failed

### ISSUE THREAD

**Issue by idnsunset** [MatsuriDayo/nekoray#135]
**描述问题**

尝试了好几个订阅定制，都是报错 `SSL handshake failed`。

**如何复现**

订阅地址不便公布，但使用 `curl <subscription_url>` 能够获取到数据。

**日志**

```
>>>>>>>> Requesting subscription: mysub
<<<<<<<< Requesting subscription mysub error: SSL handshake failed
```

**其他信息**
OS: Fedora 36
软件版本：NekoRay 2.2-2022-10-30

**Comment by idnsunset** [comment]
Thanks for the useful info that the issue is due to the bundled Qt. Although it is not difficult at all for myself to build openssl 1.1 from source and reconfigure the library load path to fix this issue, it is still a bit annoying since I have to deploy openssl 1.1 on each machine involved. Also I am recommending friends around me to migrate from qv2ray (discontinued) to nekoray on Linux, however,  a lot of them are students that are fresh new to Linux and want an application that can simply work out of box. 

BTW, is there any version of Qt that is built with openssl 3.0? If yes, is it possible to rebuild nekoray with it for release?

**Comment by madjxatw** [comment]
I am on Fedora too and there is a simple workaround for your reference:

1. Access <https://koji.fedoraproject.org/koji/buildinfo?buildID=1832791> and download the openssl-libs-1.1 rpm specific to your arch.
2. Extract `libcrypto.so.1.1.1l`, `libcrypto.so.1.1`, `libssl.so.1.1.1l` and `libssl.so.1.1` from the the rpm to `usr/lib/` directory inside your nekoray root directory.
3. Execute `./launcher` from your nekoray root directory, the openssl-1.1 libraries will be linked correctly as `usr/lib` takes precedence over the system library path by `LD_LIBRARY_PATRH` set in the launcher.

**Comment by nakdesu** [comment]
since this issue is 21 days old, the only workaround for now is using subscription convertor that allows http:// instead of forcing you to use https://
i would recommend 
https://sub.feng666.tk/
and change the generated link to http://

**Comment by Saeed-Pooyanfar** [comment]
OK, as many users reported VPN mode doesn't work correctly in Linux, [including me](https://github.com/MatsuriDayo/nekoray/issues/340), Instead of using VPN mode in `nekoray`, now I'm using `nekoray_core` to setup socks proxy then with help of `tun2socks` I achieved VPN mode in Linux via CLI (`Ubuntu 22.04 LTS` in my case)  
Here is my guide on medium:  
[**Use socks proxy as VPN in Linux**](https://medium.com/@SaeedPooyanfar/use-socks-proxy-as-vpn-in-linux-d31b1cce44e0)  
BTW @arm64v8a Thanks for `nekoray_core` 😊👍

**Comment by idnsunset** [comment]
Thanks for some useful sharing, however, I've switched to v2raya since nekoray is still immature so far.

**Comment by Hamedtbf** [comment]
> Thanks for some useful sharing, however, I've switched to v2raya since nekoray is still immature so far.

how am I able to download & use v2raya on Ubuntu?
