### ISSUE TITLE
BUG:简单路由无法工作

### ISSUE THREAD

**Issue by aavamin** [MatsuriDayo/nekoray#1362]
## 描述问题

预期行为：

实际行为：

## 如何复现

启动的时候这样提示,已经安装了Archlinuxcn sing-geoip sing-geosite 这两个包

`INFO[0000] router: updated default interface wlan0, index 3
INFO[0000] router: loaded geoip database: 250 codes
INFO[0000] router: loaded geosite database: 1326 codes
ERROR[0000] router: failed to initialize geosite: read geosite: code category-ads-all not exists!
ERROR[0000] router: failed to initialize geosite: read geosite: code cn not exists!
INFO[0000] inbound/mixed[mixed-in]: tcp server started at 127.0.0.1:10800
INFO[0000] sing-box started (0.00s)`

简单路由功能失效

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by keinoki** [comment]
试试从 Release 的 zip 把 geo 系列文件拷贝到 /usr/share/nekobox，然后卸载掉 sing-geo 系列的包
我更新完 4.0-beta3 后出现同样问题，用 Release 里面带的 geo 文件解决了

**Comment by Lsyx-Good** [comment]
目前不要使用这个[commit](https://github.com/SagerNet/sing-geosite/tree/9f8a5e7cba4f10cbb65ea2ba2ce81201bdb0595a)生成的geo资源

**Comment by canlin-github** [comment]
> 目前不要使用这个[commit](https://github.com/SagerNet/sing-geosite/tree/9f8a5e7cba4f10cbb65ea2ba2ce81201bdb0595a)生成的geo资源

所以不应该用archlinuxcn的sing-geoip和sing-geosite包么？

**Comment by aavamin** [comment]
> 试试从 Release 的 zip 把 geo 系列文件拷贝到 /usr/share/nekobox，然后卸载掉 sing-geo 系列的包 我更新完 4.0-beta3 后出现同样问题，用 Release 里面带的 geo 文件解决了

好的,按照你的方式解决了

**Comment by Jisu-Woniu** [comment]
似乎也可以通过下载 7 月 18 日之前的 geosite.db 包，然后手动覆盖实现。

例如[这个版本](https://github.com/SagerNet/sing-geosite/releases/tag/20240709143535)或[这个版本](https://github.com/xchacha20-poly1305/sing-geosite/releases/tag/202407162211)

原因是上游从 [1.10.0-alpha.22 版本](https://github.com/SagerNet/sing-box/releases/tag/v1.10.0-alpha.22)开始采用了[新的 rule set 格式](https://sing-box.sagernet.org/configuration/rule-set/source-format/#version)，而 nekobox_core 目前版本为 1.9.3

**Comment by Lsyx-Good** [comment]
> 所以不应该用archlinuxcn的sing-geoip和sing-geosite包么？

目前archcn的不建议用(太新),aur的应该可以用，我看日期是12日，应该可以

**Comment by canlin-github** [comment]
我更换了geosite和geoip文件后，nekoray不再报“ERROR[0000] router“的错误了，但是我的nekoray的简单路由仍然无法正常工作，症状是选用简单路由“绕过中国大陆”的话，所有国内网站都无法访问，Firefox显示PR_END_OF_FILE_ERROR，国外的网站可以正常访问，感觉就是直接访问方式坏掉了一样，这个症状是从4.0beta开始的，一直没好。我用的archlinuxcn的nekoray包，也提交了一个issue #1340。

所以你们的简单路由目前都工作正常？

**Comment by Lsyx-Good** [comment]
> 所以你们的简单路由目前都工作正常？

正常呀，你的日志level 应该为debug 方便查看
