### ISSUE TITLE
Nekoray crashes !

### ISSUE THREAD

**Issue by chromer030** [MatsuriDayo/nekoray#14]
Nekoray always crashes in following scenario :

Import some servers (mine are all shadowsocks) , start one of them , select the servers you imported including started one and delete them all, now start another one in the list , the Nekoray will crash !

**Comment by arm64v8a** [comment]
why you delete a running profile ?

**Comment by chromer030** [comment]
Sometimes a profile is timeout ! and user forget to stop it then remove it.

**Comment by arm64v8a** [comment]
added a check
