### ISSUE TITLE
BUG: Tune "Whitelist mode" not working

### ISSUE THREAD

**Issue by neversleeping** [MatsuriDayo/nekoray#1409]
When "Whitelist mode" checkbox in checked in Tun settings, "Proxy process name" list is just completely ignored and all traffic just goes through VPN. Blacklist mode works correctly. I tried v4.0-beta3 and 3.26 (both with sing-box core) and have this bug in both.

Expected behavior:
Only processes from white list go through VPN.

Actual behavior:
All processes go through VPN.

## How to reproduce
![изображение](https://github.com/user-attachments/assets/2b8db2b2-d719-4c1a-b218-b595a13a234d)

**Comment by FriedCheese-del** [comment]
Have you set default outbound in routing settings -> Simple Route to bypass?

**Comment by neversleeping** [comment]
> Have you set default outbound in routing settings -> Simple Route to bypass?

Wow. No, I didn't... So, TUN whitelist and blacklist settings are not standalone settings, but an override of default routing? Quite counterintuitive to me... Seems that this should be in checkbox tooltip. Anyway, thanks for info.

**Comment by Umaq12** [comment]
Hi, were you able to solve this problem?

**Comment by IvanNovR** [comment]
> Have you set default outbound in routing settings -> Simple Route to bypass?

I have the same problem. This solution did not work for me

**Comment by orange11orange** [comment]
I also couldn't figure out how to add an application (not a browser) to the whitelist.

**Comment by dvborzov** [comment]
This is how it worked for me, I had to turn off the built-in tun checkbox
enabled gVision and enabled ipv6 I don’t know what this does, but I got a white list

![image](https://github.com/user-attachments/assets/1ef78317-21c2-4082-9b43-5bc860f2c667)

**Comment by orange11orange** [comment]
Do I understand correctly that in order to add an application to the white list In Neko, I still need to set up a VPN connection in it? I can't do this because the app doesn't work properly with WireGuard (at any settings the upload speed is extremely low).
