### ISSUE TITLE
How to TUN mode for NixOS users

### ISSUE THREAD

**Issue by nekotori55** [MatsuriDayo/nekoray#1437]
I created this issue to help people who, like me, had difficulty using TUN mode on nixos (DNS problems).
You need to enable resolved for tun mode to work.
To enable resolved insert this line in your configuration.nix :
```nix
services.resolved.enable = true;
```

**Comment by khankul** [comment]
This didn't help me to enable Internal TUN with NekoBox.

**Comment by nekotori55** [comment]
> This didn't help me to enable Internal TUN with NekoBox.

yeah, I don't use internal tun

**Comment by tyasheliy** [comment]
thank you VERY much!! i have been messing with tun for 2 days and your answer just maked it work!

**Comment by zhpjy** [comment]
Thanks. But why?

**Comment by khankul** [comment]
Note: if you enabled systemd-resolved (or any other DNS resolver really) but still have no luck with TUNs, you might have the default NixOS firewall enabled. Turning the entire thing off is probably not a good idea, so try `networking.firewall.checkReversePath = "loose";`. I borrowed it from [mullvad-vpn.nix](https://github.com/NixOS/nixpkgs/blob/36864ed72f234b9540da4cf7a0c49e351d30d3f1/nixos/modules/services/networking/mullvad-vpn.nix#L43), and the relevant issue ticket [is here](https://github.com/NixOS/nixpkgs/issues/113589). 
Edit: Additionally, you might want to bypass the DNS resolver in TUN settings.
