### ISSUE TITLE
Wildcard support for routing settings

### ISSUE THREAD

**Issue by KiGamji** [MatsuriDayo/nekoray#1441]
When you add a domain in Preferences -> Routing Settings -> Simple Route, it only matches the specific domain and does not match any of the subdomains. Please make an ability to use wildcards, like `*.example.com`, or even some harder cases, such as `*example.com`, `cdn*.example.com`, etc.

**Comment by Rattge** [comment]
Hello
You can use "Custom Route (global)" option in Routes settings
![image](https://github.com/user-attachments/assets/e4dbeadd-a738-499e-a5cf-527991fa1212)


There you can use raw sing-box settings
https://sing-box.sagernet.org/configuration/route/rule/#domain_keyword
So, any requests to "play.google.com" will route through proxy

**Comment by KiGamji** [comment]
apparently it also works if I put `domain:example.com` in simple route settings. thanks!
