### ISSUE TITLE
BUG: I need help with this error

### ISSUE THREAD

**Issue by Space-00** [MatsuriDayo/nekoray#1457]
I can't connect to anything, when I hit start it gives me this error

Loadconfig return error
start service: initialize inbound/mixed[mixed-in): listen tcp 127.0.0.1:2080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted. 

What do I need to do? I need help ASAP
and by the way 127.0.0.1:2080 is not in use anywhere else on my pc so the port is free

**Comment by Space-00** [comment]
I restarted my pc and everything is fine now and the app is working like a charm

yeah, thank you for all of your HELP guys 😐😑😶🙄

**Comment by liujinyu2024** [comment]
If I restart, it's fine; otherwise, I cannot open the app. Is there a long-term solution to this problem? nekoboxstart service: initialize inbound/mixed[mixed-in]: listen tcp 127.0.0.1:5080: bind: Only one use of each socket address (protocol/network address/port) is normally permitted.
