### ISSUE TITLE
How to direct localhost and local network?

### ISSUE THREAD

**Issue by lemintare** [MatsuriDayo/nekoray#1462]
Здравствуйте, у меня проблема. Даже две. Во первых я не могу подключиться к другому устройству в локальной сети (192.168.0.x/24) пока не отключу nekoray. Во вторых у меня возникают проблемы даже при запуске локального сервера на самом устройстве (например mlflow server). Подскажите пожалуйста, что делать?

**Comment by lemintare** [comment]
Я писал в direct ip 192.168.0.0/24 но не помогает.

**Comment by ItzSkyReed** [comment]
@lemintare ты как-то пофиксил это?
