### ISSUE TITLE
BUG: DELETE ANIME IMAGE

### ISSUE THREAD

**Issue by noname123134** [MatsuriDayo/nekoray#1472]
Not everyone watches anime. If you are developing an application for public users, you should use neutral images.

**Comment by madKULOLO** [comment]
Do you seriously consider this a bug? :D

**Comment by noname123134** [comment]
> Do you seriously consider this a bug? :D

why not :) bug is not only program functionality but also a programmer

**Comment by Xoma163** [comment]
Bruh, it's open source. Fork it and compile it however you want
