### ISSUE TITLE
Tun device is gone

### ISSUE THREAD

**Issue by SpaceM1x** [MatsuriDayo/nekoray#1482]
Yesterday tun mode stopped working for some reason. I decided to restore network settings. After that Tun device was deleted and now i cant use tun mode, is there any way to create tun device again?

**Comment by SpaceM1x** [comment]
Resetting windows without deleting any files fixed the problem

**Comment by emmmahub** [comment]
> Resetting windows without deleting any files fixed the problem

hello! have the same issue. wdym resetting windows?
