### ISSUE TITLE
ERROR dns: exchange failed for *.com. IN A: Post "https://8.8.8.8/dns-query": context canceled | context deadline exceeded

### ISSUE THREAD

**Issue by laniakeadev** [MatsuriDayo/nekoray#1484]
I enable with or without the Tun mode, it work nother with it, nor without. I also enabled "sing-box" core and ebabled "Strict route" in Tun settings.

I'm getting those two errors:
`ERROR[0014] dns: exchange failed for example.org. IN A: Post "https://8.8.8.8/dns-query": context deadline exceeded`

`ERROR[0005] dns: exchange failed for go.microsoft.com. IN A: Post "https://8.8.8.8/dns-query": context canceled`

In the app settings "Remote DNS" set to deafult "https://8.8.8.8/dns-query"

I tried on two different networks, neither works.

**Comment by Nikitatut** [comment]
Found a solution?

**Comment by laniakeadev** [comment]
> Found a solution?

Yes, with finding a suitable SNI (try e.g. yahoo or google to identify)
