### ISSUE TITLE
BUG: NekoRay proxies those processes that are specified as non-proxied

### ISSUE THREAD

**Issue by Kukuryzen666** [MatsuriDayo/nekoray#1500]
## Describe the problem

After installing the program, I set the settings. Skip processes: cs2.exe
Phasmophobia.exe
He continues to proxy everything further.
In proxy mode or TUN mode, the same thing happens.

Expected behavior:

Skip games when the settings are set. I will log into the game and the game will not go through a proxy

Actual behavior:

When setting the settings to skip games, it continues to proxy them

## How to reproduce

It's easy to reproduce. Go to the TUN mode settings. Set the browser to skip processes in the parameters, apply and log in to the browser and continues to proxy

https://youtu.be/ohcKD_sVleU

## log

If you have logs, please upload them. Please see the detailed steps for exp
[neko.log](https://github.com/user-attachments/files/17836090/neko.log)
orting logs in the documentation.

**Comment by duskallegro** [comment]
I tried to make it so everything opened in Chrome browser is not accessed using VPN, but rather using my normal IP:

![image](https://github.com/user-attachments/assets/5116c0cb-5aff-44a5-b105-162142cd7ba0)

it works well. My IP address when going to websites from Chrome browser is my normal IP, and the VPS' IP when going through other browsers

**Comment by Kukuryzen666** [comment]
In any case, I have set the same settings as you have in the screenshot, the floor of the computer is proxied further
