### ISSUE TITLE
DNS Leak with version 2.3 and VPN mode

### ISSUE THREAD

**Issue by ea1234567** [MatsuriDayo/nekoray#151]
I have dns leak problem with version 2.3

I dont have problem with version 2.2

Im testing with vpn mode (proxy mode is ok and without problem)

Im using Trojan

Website for dns leak test: https://browserleaks.com/dns

**Comment by tdjnodj** [comment]
These kind of website are usually made by the VPN providers.They want to show the terrible DNS leak so that customers will buy there VPN.If you configure your routing setting right, your DNS will never leak.

**Comment by ea1234567** [comment]
But that website shows my real country (dns)

Why version 2.2 is ok? i have problem only with version 2.3

**Comment by drno88** [comment]
@arm64v8a Can you tell me what exactly this parameter does?  "Strict Route"
