### ISSUE TITLE
Help : Not running on linux ubuntu 24

### ISSUE THREAD

**Issue by lpzrulez** [MatsuriDayo/nekoray#1520]
## Describe the problem

Tried running on linux ubuntu 24 lts 
getting following error 

baby@baby:~$ ./nekoray-3.26-2023-12-09-linux-x64.AppImage --no-sandbox --disable-gpu --log-level=debug
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/baby/bins:/opt/purevpn-cli/bin:/opt/nekoray
NekoRay runing on: /tmp/.mount_nekorakjjWH4
QIODevice::read (QFile, "groups/coreType"): device not open
This plugin does not support propagateSizeHints()

please can ayone help

**Comment by LeaReXx** [comment]
any solution on ubuntu 24 LTS?

**Comment by lpzrulez** [comment]
Yes 
You need to install vnc and then use it
As it is gui it will never work as cli
