### ISSUE TITLE
Feature request: explain how to filter certain sites

### ISSUE THREAD

**Issue by Wo1fgang** [MatsuriDayo/nekoray#1544]
Good day
I know how to filter processes (like games or applications), know how to use russian sites without proxy, but I can't find reliable way to filter twitch.tv from going through proxy

![image](https://github.com/user-attachments/assets/6648410a-7b24-46ed-8604-1643079f95f1)
This way does not work for some reason, I still get ads while watching streams

Core: sing-box
Windows 10

**Comment by devopg** [comment]
This works for part of Twitch, for all parts of the resource change you line with twitch to:  `geosite:twitch`

**Comment by Wo1fgang** [comment]
Oh damn, it's actually works, thank you so much!
