### ISSUE TITLE
BUG: LoadConfig return error WIN10

### ISSUE THREAD

**Issue by proudbro** [MatsuriDayo/nekoray#1548]
## Describe the problem

Can't load PROFILE settings after the last app update

Actual behavior: 
![image](https://github.com/user-attachments/assets/6c9e17f1-ebf7-44f5-9cf1-a9fabb405be8)

## How to reproduce

When i try to connect to server

**Comment by antlu** [comment]
Launching with nekoray.exe? Launch nekobox.exe.

**Comment by proudbro** [comment]
@antlu , no, i'm launching both and have the same error

UPD: yes, finally it helps, thx
