### ISSUE TITLE
BUG: SSL Errors: The peer did not present any certificate

### ISSUE THREAD

**Issue by vollodin61** [MatsuriDayo/nekoray#1569]
When trying to add a new profile, «Program —> Add profile from clipboard», an error appears:

***
>>>>>>>> Requesting subscription: https://... .axonet.ru:8443/...
SSL Errors: The peer did not present any certificate
<<<<<<<< Requesting subscription https://... error: SSL handshake failed
***

There is an SSL certificate issued by Google Trust Services on domain axonet.ru.

What could be causing this error?

The v2RayTun application on the Android smartphone works with this profile.

I use Manjaro Linux. NekoBox version 4.0.1.
Tried installing using yay. Also tried using AppImage (TUN mode does not work when launched). Also tried extracting from .zip (this method works, but the error remains).
Before each reinstallation, I cleared the cache and deleted all files related to nekoray.

What are the possible causes of such an error? What could prevent the SSL handshake?

**Comment by vollodin61** [comment]
I tried this same profile with the [Hiddify](https://github.com/hiddify/hiddify-app/blob/main/README_ru.md) app, and it worked there.

**Comment by Fido6** [comment]
> 'Also tried extracting from .zip (this method works, but the error remains).'

may be you need build it by yourself due to different versions of protobuf between builder's system and yours.

**For SSL PROBLEM**,
trying to enable 'ignore ...TLS ....' / 'ignore ...SSL ....' under “subscription” Tab in preference，and try importing subscription again，it might be ok.

**Comment by vollodin61** [comment]
ssl problem solved successfully! Thank you!

**Comment by Alex-AXO** [comment]
> > 'Also tried extracting from .zip (this method works, but the error remains).'
> 
> may be you need build it by yourself due to different versions of protobuf between builder's system and yours.
> 
> **For SSL PROBLEM**, trying to enable 'ignore ...TLS ....' / 'ignore ...SSL ....' under “subscription” Tab in preference，and try importing subscription again，it might be ok.

Can you tell me how to solve this problem on the server side (Marzban V2Ray VLESS), what needs to be changed? If you know?

**Comment by Fido6** [comment]
> > > 'Also tried extracting from .zip (this method works, but the error remains).'
> > 
> > may be you need build it by yourself due to different versions of protobuf between builder's system and yours.
> > 
> > **For SSL PROBLEM**, trying to enable 'ignore ...TLS ....' / 'ignore ...SSL ....' under “subscription” Tab in preference，and try importing subscription again，it might be ok.
> 
> Can you tell me how to solve this problem on the server side (Marzban V2Ray VLESS), what needs to be changed? If you know? 

Sorry, sir, I have no server-side configuration experience at present, so I can't help you.

**Comment by liveevildevil** [comment]
> > 'Also tried extracting from .zip (this method works, but the error remains).'
> 
> may be you need build it by yourself due to different versions of protobuf between builder's system and yours.
> 
> **For SSL PROBLEM**, trying to enable 'ignore ...TLS ....' / 'ignore ...SSL ....' under “subscription” Tab in preference，and try importing subscription again，it might be ok.

it works thx :>>
