### ISSUE TITLE
[Windows] Can't activate VPN mode [Solved]

### ISSUE THREAD

**Issue by maaaAMA** [MatsuriDayo/nekoray#200]
Hi,

I'm a **Windows** user, not **Linux**, and I'm not able to activate VPN mode anymore after restarting the computer while Nekoray was still running. I'm also unable to use any other V2Ray core-based client as well, as they all give Kernel failure errors. I'm willing to provide more info if required. I appreciate any assistance or temporary fix.

Additional info:
CMD launches after attempting to activate "VPN mode" and closes after a few moments; this is what it shows:
> 
> 2022/12/06 03:52:56 underlyingDNS: {f627d343-a35b-46b2-8776-4d36311fe97f} 192.168.1.1
> sing-box: 1.1 Neko: nekoray-2.7-2022-12-04
> 
> INFO[0000] router: updated default interface Ethernet 2, index 21

I've already tried:

- Network adaptors drivers reinstall
- Network reset
- Windows repair and host file repair
- Registry clean up

Other tested clients based on V2Ray:

- Netech
- Qv2ray
- V2RayN

**Comment by VahidJavanmard** [comment]
Hi 
I Had Same Problem  With These Log

←[36mINFO←[0m[0000] router: updated default interface Ethernet, index 22
←[31mFATAL←[0m[0001] start service: initialize inbound/tun[0]: configure tun interface: set ipv4 dns: The RPC server is unavailable.

**Comment by amirsolo** [comment]
> Hi I Had Same Problem With These Log
> 
> ←[36mINFO←[0m[0000] router: updated default interface Ethernet, index 22 ←[31mFATAL←[0m[0001] start service: initialize inbound/tun[0]: configure tun interface: set ipv4 dns: The RPC server is unavailable.

@VahidJavanmard Have you fixed your issue?
I'm running into a similar issue. When clicking on the VPN mode, the terminal opens but then exits immediately after showing the below message:
```bash
2023/02/03 00:36:35 underlyingDNS: {*******} ******
sing-box: 1.1.4 Neko: nekoray-2.13-2023-01-31

INFO[0000] router: updated default interface Wi-Fi, index 18
```
I really need to tunnel my entire system and the for now the only available option I have is this feature of NekoRay which has been giving me this error recently.

**Comment by AleTTA3** [comment]
I have This problem

←[36mINFO←[0m[0000] router: updated default interface Ethernet, index 16
←[31mFATAL←[0m[0001] start service: initialize inbound/tun[0]: configure tun interface: set ipv4 dns: The service has not been started.

**Comment by alihassan78611092** [comment]
when i start my config it shows me this



INFO[0004] [206243479 0ms] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:51012
INFO[0004] [206243479 0ms] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0004] outbound/vless[proxy]: outbound connection to 8.8.8.8:443
INFO[0004] outbound/vless[proxy]: outbound connection to 8.8.8.8:443
ERROR[0005] dns: exchange failed for mtalk.google.com. IN A: Post "https://8.8.8.8/dns-query": EOF
INFO[0005] [2572342939 0ms] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:54738
INFO[0005] [2572342939 0ms] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0005] outbound/vless[proxy]: outbound connection to 8.8.8.8:443
INFO[0005] outbound/vless[proxy]: outbound connection to 8.8.8.8:443
ERROR[0005] dns: exchange failed for www.msftconnecttest.com. IN A: Post "https://8.8.8.8/dns-query": EOF

**Comment by alihassan78611092** [comment]
when i start my config it shows me this and my wifi get disconected


INFO[0004] [206243479 0ms] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:51012
INFO[0004] [206243479 0ms] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0004] outbound/vless[proxy]: outbound connection to 8.8.8.8:443
INFO[0004] outbound/vless[proxy]: outbound connection to 8.8.8.8:443
ERROR[0005] dns: exchange failed for mtalk.google.com. IN A: Post "https://8.8.8.8/dns-query": EOF
INFO[0005] [2572342939 0ms] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:54738
INFO[0005] [2572342939 0ms] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0005] outbound/vless[proxy]: outbound connection to 8.8.8.8:443
INFO[0005] outbound/vless[proxy]: outbound connection to 8.8.8.8:443
ERROR[0005] dns: exchange failed for www.msftconnecttest.com. IN A: Post "https://8.8.8.8/dns-query": EOF

**Comment by furrycoding** [comment]
> Hi I Had Same Problem With These Log
> 
> ←[36mINFO←[0m[0000] router: updated default interface Ethernet, index 22 ←[31mFATAL←[0m[0001] start service: initialize inbound/tun[0]: configure tun interface: set ipv4 dns: The RPC server is unavailable.

@VahidJavanmard 

After countless hours on this problem, I finally found the reason for this error: the Dnscache (DNS Client) windows server isn't running
You need to enable it and restart the system, afterwards it should be running and the "RPC server is unavailable error" should be gone
This case should really be documented somewhere
