### ISSUE TITLE
[Feature Request] Can't reopen Nekoray from the taskbar in Linux(Gnome) after closing it

### ISSUE THREAD

**Issue by alimodev** [MatsuriDayo/nekoray#205]
If you close Nekoray in Linux (Ubuntu), the app minimizes to the taskbar, but when you click on the icon, there is no option to open the main window in the menu that appears! The trick is to click on "Scan QR Code" to open the main window and close the error dialog afterwards.

It would be nice to have a "Open Window" at the top of this menu.

![image](https://user-images.githubusercontent.com/53017782/206453737-37d1f8ff-2c67-42cb-8bba-4c41622ceb24.png)

**Comment by DarkReaperBoy** [comment]
just double click the icon on tray

**Comment by alimodev** [comment]
In ubuntu 22.04, double clicking only toggle the menu open and close, no matter how fast you double click. It works in version 20.04 though, but the expected UI/UX behavior is single clicking for opening the main window and right click for the context menu.
Other apps like Qv2ray also have a "Show" Item at the beginning of the context menu.

**Comment by alimodev** [comment]
https://user-images.githubusercontent.com/53017782/208785277-5701e99c-2beb-460d-bcf5-820eac0f339c.mp4

**Comment by papampi** [comment]
If you start it with sudo from command line,  clicking taskbar icon will minimize it to taskbar and restore it.
Also it wont ask for password for starting vpn.

**Comment by moeiniamir** [comment]
It seems to be very easy to implement. I know nothing about QT but would do it if someone suggests where to start.
