### ISSUE TITLE
Importing SSR from Clipboard not working

### ISSUE THREAD

**Issue by APT-ZERO** [MatsuriDayo/nekoray#216]
Add SSR support please. Thank you.

**Comment by tdjnodj** [comment]
In shadowsocks' setting,find the "plugin".Then you can use ssr

**Comment by tdjnodj** [comment]
![plugin](https://raw.githubusercontent.com/tdjnodj/picture_bed/main/issue/2022121001.png)
try set it here

**Comment by DarkReaperBoy** [comment]
But does not import from clipboard

**Comment by Yasin-Dev81** [comment]
This problem has been solved in the Windows version, but it still exists in the Linux version:(

**Comment by maxorbase** [comment]
please fix this issue on Linux version
