### ISSUE TITLE
Change text colors for 'blacksoft' theme

### ISSUE THREAD

**Issue by APT-ZERO** [MatsuriDayo/nekoray#217]
![image](https://user-images.githubusercontent.com/41063376/206854222-b4536785-a2ce-47f4-949f-86e24f4698b7.png)
![image](https://user-images.githubusercontent.com/41063376/206854252-8f0a18ad-e14c-4264-beef-32c92efb332d.png)

Can't read because text colors are too dark

**Comment by TheWeirdDev** [comment]
I have the same issue. The text is very hard to read.
