### ISSUE TITLE
i cant run it on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by ali-ashhar** [MatsuriDayo/nekoray#260]
i install libxcb-xinerama0 but still cant run the program.
following errors:

$ ./nekoray
./nekoray: error while loading shared libraries: libQt5Network.so.5: cannot open shared object file: No such file or directory

**Comment by ohmydevops** [comment]
```sudo apt install libqt5network5 libqt5widgets5 libqt5widgets5 libqt5x11extras5```
