### ISSUE TITLE
VPN mode failed

### ISSUE THREAD

**Issue by AliDoostar** [MatsuriDayo/nekoray#265]
[Error] app/dns: failed to retrieve response > Post "https://8.8.8.8/dns-query": context deadline exceeded

 i get this error

**Comment by SafaSafari** [comment]
Try change remote dns option in routing setting to 1.1.1.1 or 8.8.8.8 (whitout https)
Also enable enhaced ... Check box

**Comment by parsafaramarzi** [comment]
Fixed the issue for me thanks mate.
