### ISSUE TITLE
希望能支持X2RAY核心最新的xtls-rprx-vision流控

### ISSUE THREAD

**Issue by realtonyig** [MatsuriDayo/nekoray#279]
**描述建议**
希望能支持X2RAY核心最新的xtls-rprx-vision流控。 非常感谢
**建议的必要性**
最新的流控
介绍如下
https://github.com/XTLS/Xray-core/discussions/1295

**Comment by tdjnodj** [comment]
建议你先搞懂v2Ray和xray的区别，再来看看nekoray的介绍
