### ISSUE TITLE
关于hysteria mapping port的问题

### ISSUE THREAD

**Issue by nzcool** [MatsuriDayo/nekoray#283]
配置文件 格式
{
"server": "us.iooj.cc:19539,25000-30000",
"protocol": "udp",

如果写成
{
"server": "us.iooj.cc:%mapping_port%",
"protocol": "udp",

后
编辑页面内的 Mapping Port*框无法写入19539,25000-30000 这样的端口

**Comment by tdjnodj** [comment]
端口跳跃要在hysteria里配置，不要用外部映射。
