### ISSUE TITLE
Automatic Reconnect

### ISSUE THREAD

**Issue by Stevemoretz** [MatsuriDayo/nekoray#300]
I'm on MacOS Catalina 10.15

I'm not sure if you have this feature available or not, but a lot of times it stops working after a while and I have to manually right click and start the config, would be great if it could retry it by itself :)

These are the last messages I get before it stops, I have not enabled the VPN mode or System Proxy mode, I use socks to connect to nekoray.

And after I start it again (By right click on config and press start), it immediately starts working so no connection issues is keeping it from not retrying either.

```
Exit due to inactive
>>>>>>>> Starting profile [VLESS] Use+intermidate+website
>>>>>>>> Stopping profile [VLESS] Use+intermidate+website
[Error] core exited, restarting.

[Error] gRPC: QNetworkReply::NetworkError code: -1919

[Error] gRPC: QNetworkReply::NetworkError code: -1919
```

**Comment by razielaka** [comment]
Great app, thanks to the dev!
Similar to this problem, when Nekoray starts with Windows, I believe it starts before Windows has network access so it gives the following error and doesn't work unless you restart the proxy by opening Nekoray and pressing enter, for example.
![image](https://user-images.githubusercontent.com/9019679/213404913-15e1f826-be55-45b4-8463-2665501b7480.png)

An optional pause for a few seconds after starting Nekoray, or even better, an algorithm to check for network access before starting the proxy, or even an option to check that the server/connection has internet access and restart or change to another connection that does have access could fix the issue. This could be automatic or based on user preferences.

**Comment by Stevemoretz** [comment]
> Great app, thanks to the dev! Similar to this problem, when Nekoray starts with Windows, I believe it starts before Windows has network access so it gives the following error and doesn't work unless you restart the proxy by opening Nekoray and pressing enter, for example. ![image](https://user-images.githubusercontent.com/9019679/213404913-15e1f826-be55-45b4-8463-2665501b7480.png)
> 
> An optional pause for a few seconds after starting Nekoray, or even better, an algorithm to check for network access before starting the proxy, or even an option to check that the server/connection has internet access and restart or change to another connection that does have access could fix the issue. This could be automatic or based on user preferences.

I see your point what you are describing might need a retry feature too, but my case is a little different it happens when I'm connected to the internet and nekoray and then after a while it just happens...

**Comment by Stevemoretz** [comment]
Updated to latest version of Nekoray and so far haven't had the issue!

**Comment by Stevemoretz** [comment]
Yeap still no problem with the latest version, closing this...
