### ISSUE TITLE
[Linux] Vpn mode dosen't turn on

### ISSUE THREAD

**Issue by goatmmd** [MatsuriDayo/nekoray#309]
when I want to turn on the VPN mode after starting the server it doesn't work 
Ubuntu 22 LTS

**Comment by arianaminiss** [comment]
in your main network drive go to setting then do these
internet protocol version 4 (TCP/IPV4)
then at bottom right click on advance
then uncheck automatic metric
type 99 in that field and click ok
1 time restart your system then vpn mode will fix

> when I want to turn on the VPN mode after starting the server it doesn't work Ubuntu 22 LTS

**Comment by AmirHosseinKarimi** [comment]
Hey. Check [this](https://github.com/MatsuriDayo/nekoray/issues/337#issuecomment-1411570402).

**Comment by far1dghaderi** [comment]
change the core to sing-box. It fixed my problem.
