### ISSUE TITLE
[windwos] VPN Mode Problem

### ISSUE THREAD

**Issue by AnotherAH** [MatsuriDayo/nekoray#314]
I have a bizarre problem with the VPN mode
first I have to say the problem is not nekoray but I think here is the best place to find a solution 

so everything works just fine, I turn it on and the interface comes up and works but my system is not using it
and it becomes weirder when I go to whatismyip site, in this site it says my VPN IP and its normal
but anywhere else like speedtest.net says my real IP and its not working with nekoray-tun 
also, not a single blocked site or app is working [it's like I'm not using nekoray-tun]

I test it on a different system and it works just fine
please if you know how to solve this problem or want more information tell me

**Comment by Elidlt** [comment]
Hi this work for me in face of this problem.
in the **Routing Setting** change **Outbound Domin Strategy** to that Ip where Showing in whatismyip site.
for me that was Ipv4
![image](https://user-images.githubusercontent.com/26128345/214956094-1b0a89c1-f97f-4a3e-8a1f-a96281d0b5b4.png)


> I have a bizarre problem with the VPN mode first I have to say the problem is not nekoray but I think here is the best place to find a solution
> 
> so everything works just fine, I turn it on and the interface comes up and works but my system is not using it and it becomes weirder when I go to whatismyip site, in this site it says my VPN IP and its normal but anywhere else like speedtest.net says my real IP and its not working with nekoray-tun also, not a single blocked site or app is working [it's like I'm not using nekoray-tun]
> 
> I test it on a different system and it works just fine please if you know how to solve this problem or want more information tell me

**Comment by AnotherAH** [comment]
changing the outbound domain strategy didn't help it
not even https://whatismyipaddress.com/ says my real IP

as you see my nekoray-tun interface is connected and should work but it's not routing anything
![image](https://user-images.githubusercontent.com/70831339/214962066-6f8d4dfc-95eb-4500-a7dc-ca254fcaebef.png)

**Comment by arianaminiss** [comment]
> changing the outbound domain strategy didn't help it not even https://whatismyipaddress.com/ says my real IP
> 
> as you see my nekoray-tun interface is connected and should work but it's not routing anything ![image](https://user-images.githubusercontent.com/70831339/214962066-6f8d4dfc-95eb-4500-a7dc-ca254fcaebef.png)

At this image you have 2 network dont make any change on nekoray-tun go to AH Private Network setting click on
internet protocol version 4 (TCP/IPV4)
then at bottom right click on advance
then uncheck automatic metric
type 99 in that field and click ok 
1 time restart your system then vpn mode will fix

**Comment by AnotherAH** [comment]
changing the metric for interface in ipv4 solves the problem
thank @arianaminiss
