### ISSUE TITLE
删除重复配置判断条件依据是否过于简单？会将实际不同的节点删除。

### ISSUE THREAD

**Issue by Bbeginnerr** [MatsuriDayo/nekoray#317]
对于优选IP的VMESS节点，不同节点地址端口及UUID虽然一致，但host地址及SNI地址是不同的，使用删除重复配置这一功能会把地址端口及UUID一致的节点均视为重复配置，被误删除。
       希望可以改进判断重复配置的条件。

**Comment by purofle** [comment]
最新版已无法复现
