### ISSUE TITLE
Support ShadowsocksR ( SSR )

### ISSUE THREAD

**Issue by APT-ZERO** [MatsuriDayo/nekoray#326]
Support ShadowsocksR ( SSR )

**Comment by tdjnodj** [comment]
https://matsuridayo.github.io/m-configuration/#shadowsocksr

>  - 拥有 Shadowsocks 的几乎所有问题
> - 由于众所周知的原因，上游 shadowsocksr-libev 自 2017 年开始 不再维护

> - Has almost every problem with Shadowsocks
> - Upstream shadowsocksr-libev is no longer maintained since 2017 for well-known reasons
