### ISSUE TITLE
Nekoray VPN mode doesn't work in Ubuntu 22.04

### ISSUE THREAD

**Issue by AmirHosein-Gharaati** [MatsuriDayo/nekoray#337]
Nekoray does not work well on vpn mode. I use ssh port forwarding and nekoray together to connect to my server via ssh.
The profile is a Socks type. This worked well on Manjaro Linux but in Ubuntu 22.04 does not work.
I think the VPN mode has something wrong with it. v2ray config does not work neither.

**Expected behavior**:
I expected nekoray works well in VPN mode in Ubuntu 22.04.
Used released version in linux.

**Actual behavior**:
VPN mode starts and accepts regular traffics but to the one I configured in my profile.
When clicking on VPN mode, it starts and remains enable but doesn't work actually.

**Comment by AmirHosein-Gharaati** [comment]
I just figured out that google chrome and firefox don't use nekoray tunnel, but another app like telegram desktop worked well.

**Comment by tdjnodj** [comment]
Try to use root?Or choose 'Strict route` ?

**Comment by AmirHosein-Gharaati** [comment]
> Try to use root?Or choose `Strict route` ?Or close `Whitelist Mode`?

`Strict route` and `root` did not work. I didn't find `Whitelist Mode`.

Another thing to mention:
Setting a proxy in default `2080` port works well in google chrome. But still nekoray doesn't tunnel.

**Comment by tdjnodj** [comment]
OK,now I get the same problem,too.Then I restart the VPN mode several times.And it worked.

If it doesn't work,try to restart it.

**Comment by AmirHosseinKarimi** [comment]
I faced this problem several times and found it's from the Nekoray tun interface.
I don't know why and how this happens, but it happens sometimes.
To fix this issue I close Nekoray app and then remove `nekoray-tun` interface via following command:
```bash
sudo ip link delete nekoray-tun
```
Then launch the app and enable VPN mode.

**Comment by tdjnodj** [comment]
The problems of VPN mode in Ubuntu may were cased by the DNS setting of Ubuntu.I found that the system is listening 127.0.0.1:53.And when I using 'dig' with VPN mode,I get the DNS leak.

After that I change my DNS setting in `/etc/systemd/resolved.conf`.And the DNS leak situation disappeared.I can use VPN mode normally,too.

**Comment by d3ath3ater79** [comment]
install version 2.17 , it works well

**Comment by shabihish** [comment]
The problem might be with your Nekoray path having a space in it. Nekoray VPN mode uses `cd path_to_your_dir` without quotations, which could cause an error if there are spaces in the path resulting in multiple params being given to `cd`.

**Comment by imalirezapy** [comment]
first start any server , in nekoray go   ` Preferecens -> Basic settings -> Common ` copy **Listen address** (most times is `127.0.0.1`) , **HTTP port &** **Socks Listen Port**.
change **Netowork Proxy**  from Linux Settings to **manual** and paste Listen address and ports 
then only enable system proxy in nekoray app.

_if didn't work try these ports_
```
Socks Listen Port: 10808
HTTP Listen Port: 10809
```

**Comment by AmirHosein-Gharaati** [comment]
This issue has been resolved. Just use latest version of nekoray.

**Comment by AmirHosein-Gharaati** [comment]
This issue has been resolved. Just use latest version of nekoray.

**Comment by ahAskari** [comment]
> install version 2.17 , it works well

it's worked for me👍

**Comment by Mehrab-Farhadzadeh** [comment]
I tried in-app Troubleshooting in Preferences > Tun Settings and it worked.

**Comment by Andrei-user** [comment]
you need to log into the super user's environment in the terminal `sudo su` and run your command
