### ISSUE TITLE
No icon on Wayland

### ISSUE THREAD

**Issue by MasterKia** [MatsuriDayo/nekoray#341]
When using the program on Wayland, there's no icon on the task manager and the generic Wayland icon is shown instead.

![1](https://user-images.githubusercontent.com/17685483/216040095-8fb0e74e-f064-41f8-80f1-360aa025b0f5.jpg)

KDE Plasma 5.26.5
Nekoray 2.9

**Comment by Bryan2333** [comment]
Same situation here on Gnome Wayland.

![截图 2023-02-07 21-55-34](https://user-images.githubusercontent.com/31512600/217264732-965dd0d9-64d0-4294-bfaa-07c4b57601a4.png)
