### ISSUE TITLE
Tunnel DNS requests through the VPN interface (systemd-resolved)

### ISSUE THREAD

**Issue by MasterKia** [MatsuriDayo/nekoray#342]
When using the VPN mode of Nekoray on GNU/Linux, DNS requests go through the default interface and not through nekoray-tun.

<details>
<summary>resolvectl status</summary>

```
Global
       Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (wlp3s0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.0.1
       DNS Servers: 192.168.0.1

Link 4 (nekoray-tun)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

</details>

Notice the `-DefaultRoute` for nekoray-tun even though VPN Mode is activated.

Half-solution:
```
resolvectl domain nekoray-tun '~.'
resolvectl default-route nekoray-tun true
resolvectl dns nekoray-tun 1.1.1.1
resolvectl default-route wlp3s0 false
```

Although I think this will interfere with Nekoray's own "DNS routing".

Ultimately Nekoray should implement:
https://github.com/systemd/systemd/blob/master/docs/RESOLVED-VPNS.md

Or without that, at least do the required `resolvectl` calls.

Fedora 37 KDE
Using `systemd-resolved`
Nekoray 2.9

**Comment by imanhavangi** [comment]
Encountered the same issue and successfully resolved it within the application by following these steps:

1. Open Nekoray.
2. Navigate to Preferences -> Routing Settings -> DNS.
3. Modify the Direct DNS setting by selecting "223.5.5.5" from the dropdown menu (you may want to experiment with other options).

After making these changes, restart Nekoray and attempt to connect to your profile.

**Comment by ErfanRasti** [comment]
> Encountered the same issue and successfully resolved it within the application by following these steps:
> 
> 1. Open Nekoray.
> 2. Navigate to Preferences -> Routing Settings -> DNS.
> 3. Modify the Direct DNS setting by selecting "223.5.5.5" from the dropdown menu (you may want to experiment with other options).
> 
> After making these changes, restart Nekoray and attempt to connect to your profile.

You saved me bro. Where did you find that DNS address?
