### ISSUE TITLE
Homebrew method for install

### ISSUE THREAD

**Issue by MohamadKh75** [MatsuriDayo/nekoray#345]
Hey

Thanks for your awesome project!

As a macOS user, are there any plans to add a [homebrew](https://brew.sh) method to install it?

**Comment by tdjnodj** [comment]
See here: https://github.com/tdjnodj/homebrew-nekoray

In my fork,I will provide build for macOS.But I am not sure it can work well.

**Comment by MohamadKh75** [comment]
Thanks! ❤️
