### ISSUE TITLE
希望DNS分流的设置能够细化下

### ISSUE THREAD

**Issue by EsuRt** [MatsuriDayo/nekoray#348]
**描述建议**
能够根据自定义规则，设置不同的DNS，类似Qv2ray那样的设置。
![1](https://user-images.githubusercontent.com/15177069/216544101-25ecfb77-1861-4275-b3e8-2586a77cc8d9.jpg)

**建议的必要性**
为了应对比较复杂的使用场景，如局域网，有些局域网会自行配备DNS，方便访问内网网站。如果所有国内所有网站都经过局域网的DNS，可能造成信息泄露，因此比较合适的方案是内网网站走内网DNS，其他国内网站走国内DOH，国外网站走国外DNS。

**Comment by tdjnodj** [comment]
不如用 Qv2ray 的复杂配置。这个可以自定义一个配置组，可以有复杂分流、复杂 DNS 等

**Comment by EsuRt** [comment]
> 不如用 Qv2ray 的复杂配置。这个可以自定义一个配置组，可以有复杂分流、复杂 DNS 等

Qv2ray 已经无人维护了，遇到的bug挺多了，所以转向Nekoray了。
