### ISSUE TITLE
Some issues in Ubuntu OS

### ISSUE THREAD

**Issue by MikoyChinese** [MatsuriDayo/nekoray#369]
Env:
- nekoray version: 2.14
- OS: Ubuntu 22.04 and Ubuntu20.04

Issues:
1. I can't open the Home gui window by clicking the icon on top bar if I minimize the gui on Ubuntu22.04, but it works on Ubuntu20.04.
2. If I have a running server which from a subscribe link, and I update this subscribe by right clicking on Groud list -> Current Group -> Update subcription. It will not remove the running server and append it again. So I only remove one of it.
3. There has some difference between Routing Setting of nekoray and V2ray-core. For me, I choose `Bypass Lan and China` and `IPIfNotMatch`, but I found if a domain not in geosite:cn and ip in geoip:cn, it will be in proxy route, unless I choose `IPOnDemand strategy`.

**Comment by tdjisdj** [comment]
> If I have a running server which from a subscribe link, and I update this subscribe by right clicking on Groud list -> Current Group -> Update subcription. It will not remove the running server and append it again. So I only remove one of it.

This is not a bug, but a feature to prevent accidental deletion of the server.

> There has some difference between Routing Setting of nekoray and V2ray-core. For me, I choose Bypass Lan and China and IPIfNotMatch, but I found if a domain not in geosite:cn and ip in geoip:cn, it will be in proxy route, unless I choose IPOnDemand strategy.

You can chang the `Defauld Outbound`.
