### ISSUE TITLE
Minimize VPN Mode window to system tray

### ISSUE THREAD

**Issue by thisisamirmaleki** [MatsuriDayo/nekoray#370]
Hello,
Thanks for the nice app you developed. I'm using the Windows version as a whole system VPN program. The only issue here is when you open VPN mode, the `nekobox_core.exe` is always stuck on taskbar. It would be a huge plus if it could be minimized to tray or just don't show up.

**Comment by tdjisdj** [comment]
Related settings is in `VPN setting`.You can hide it with a setting.

**Comment by thisisamirmaleki** [comment]
> Related settings is in `VPN setting`.You can hide it with a setting.

My bad... I'm closing this issue.
