### ISSUE TITLE
编译更新

### ISSUE THREAD

**Issue by avboy1337** [MatsuriDayo/nekoray#375]
**描述问题**
In file included from /home/avboy/Desktop/nekoray/ui/mainwindow.cpp:25:
/home/avboy/Desktop/nekoray/3rdparty/ZxingQtReader.hpp:72:18: error: ‘DecodeStatus’ has not been declared in ‘ZXing’
   72 |     using ZXing::DecodeStatus;

预期行为：
no error 
实际行为：
report error
**如何复现**

Zxing最新版编译出错

**日志**

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by avboy1337** [comment]
谢谢，我去试试。OK了我立刻关闭issue

**Comment by tdjnodj** [comment]
这一更新搞的我用包管理器装的 zxing 不能用了......
