### ISSUE TITLE
Add a new test method

### ISSUE THREAD

**Issue by APT-ZERO** [MatsuriDayo/nekoray#387]
Hello, Please add a new test to check if each config can load a web page or not
It can be a URL from Google / Youtube or any webservice that user like to be able to use + a Success Key from that webpage
for example :
Webpage URL : "https://www.google.com/"
Success Key : "title>Google"
If config was able to load the webpage and the Success Key was there inside it, if means that config can load that website with no problem.

**Comment by tdjnodj** [comment]
Open `Basic Settings` .Then change your `test URL` to `truehttps://www.google.com/`

**Comment by tdjnodj** [comment]
> what is `truehttps`? how is it working? is it looking for 200 http status code? or any http status code? or something else?

IDK.You can see here: https://matsuridayo.github.io/n-configuration/#url

But it seemed just doing TLS handshak,didn't get the status code? @arm64v8a
