### ISSUE TITLE
[Feature Request]能否考虑增加导出及导入所有配置的菜单项？

### ISSUE THREAD

**Issue by egg1234** [MatsuriDayo/nekoray#407]
**描述建议**
增加导出及导入所有配置的菜单项，包括软件本身的所有配置，所有分组名字及分组内所有代理配置

**建议的必要性**
随着软件日趋完善，很多用户已经跟随nekoray更新版本，但是每次更新版本，都要重新做一次软件本身的软件设置，重新创建分组，然后再从旧版软件导出分组内的代理配置，再导入到新软件的对应分组，这整个过程比较麻烦，希望考虑用户升级版本时的便利性

谢谢！

**Comment by tdjnodj** [comment]
那是你更新得不对。把新版的 zip 包放在 nekoray 同目录，然后运行 'update' 就能更新了。

**Comment by tdjnodj** [comment]
> 我原来的nekoray是2.11[windows版]，运行文件放在d:\nekoray2.11目录里面，然后按照你的方法把nekoray-2.17-2023-02-25-windows64.zip文件拷贝到d:\nekoray2.11目录里面，在d:\nekoray2.11目录里面点击updater.exe运行，结果只会拷贝出一个updater.old文件，原来2.11的所有文件完全没有变化，也没有释放出2.17的任何文件，想请问这个目录结构有什么讲究的吗？

那我不清楚了。在 linux 中，把 zip 文件放到 nekoray 目录，再运行 update 就能升级。是不是没退出主程序？

参考: https://matsuridayo.github.io/n-faq/#_8
