### ISSUE TITLE
Sort by delay results not working properly

### ISSUE THREAD

**Issue by pulsarice** [MatsuriDayo/nekoray#413]
in v 2.17 I want to sort by server delay, but servers are sorted in different chunks! each chunk is sorted, but that's not the way it's supposed to work.
As you can see row 18 has a less delay than some of the rows above:

![image](https://user-images.githubusercontent.com/5326305/221978540-36779fa3-2534-4c50-8956-260624ae058a.png)

**Comment by EzSync** [comment]
Yes, you are right. But it will work properly if you delete unavailable results.
