### ISSUE TITLE
[Windows] VPN Mode not working

### ISSUE THREAD

**Issue by smm-h** [MatsuriDayo/nekoray#447]
I am using the latest version (2.19) in Windows, and when I click on the VPN Mode checkbox, it asks for administrator permissions, I click Yes, it checks, a console window pops up, the console window disappears by itself after about one second, and the **VPN mode checkbox is automatically unchecked**.

I used an elevated CMD and the `nekobox_core.exe run -c config/sing-box-vpn.json` command to see what the console window log says:

```
←[36mINFO←[0m[0000] router: updated default interface Wi-Fi, index 21
←[31mFATAL←[0m[0002] start service: initialize inbound/tun[0]: configure tun interface: set ipv4 address: The object already exists.
```

Apparently some object exists and it is trying to recreate that object. The problem might be resolved if I find and delete that object manually somehow. **Restarting the program, restarting the computer, reinstalling the program** have been **unsuccessful** in resolving the issue.

It might be worth noting that everything was working fine until yesterday; I don't know what changed.

All help is appreciated!

**Comment by smm-h** [comment]
I figured it out!

I just deleted the relevant subfolders in each of the following registry addresses using `regedit`:

- `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Profiles\`
- `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Signatures\Unmanaged`
- `Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\SharedAccess\Parameters\FirewallPolicy\FirewallRules`

**Note that you should delete only the one subfolder related to nekoray and not the other ones!**

After this, I restarted the computer, and when I ran Nekoray again (without even reinstalling it), it asked for network permissions and everything including the VPN Mode worked fine again.

Hope this helps!

**Comment by minzdrav** [comment]
Hi @smm-h 
Thank you for your trick! You saved my day.
Can you reopen the issue?
I mean this bug happened to me today and may occur to any user. It would be nice to fix the bug in the application.

**Comment by smm-h** [comment]
@minzdrav are you using the latest version? I am, and I haven't encountered the bug in a long time. If you are, and it still happens, let me know so I can reopen the issue.

**Comment by minzdrav** [comment]
@smm-h yes, latest version. Looks like this bug is rare, but still exists.

**Comment by theAester** [comment]
Hi. For anyone else who has made the GRAVE mistake of shutting down windows when VPN mode was running, if you're not in the mood to do registry hack mentioned before, a quick temporary fix would be to navigate to your nekoray folder in an administrator powershell instance. edit the `config/sing-box-vpn.json` file. below the line that says 'nekoray-tun' is an IP address, change that from 172...1/28 to 172...2/28. then from your admin powershell run `./nekobox_core.exe run -c ./config/sing-box-vpn.json` and it will work. Do not attempt to use the `VPN mode` switch in the application as it overrides the changes you made in the sing-box config file.

**Comment by est412** [comment]
> subfolder related to nekoray

Hi! How to know the registry subfolders related to nekoray?

**Comment by est412** [comment]
Hi!
The problem in Windows is the existence of the 172.19.0.1 route created by Hyper-V. It's the case when you use Docker for windows for example.
One can check it using `route print` and `ipconfig /all` commands.
Permanent and reliable workaround is direct patching nekobox.exe file by replacing `172.19.0.1/28` substring with `172.19.0.2/28` or some next available IP.
