### ISSUE TITLE
为Tun增加权限

### ISSUE THREAD

**Issue by lonble** [MatsuriDayo/nekoray#450]
**描述建议**

操作系统: Arch Linux
安装方式: AUR nekoray-bin
桌面环境: KDE Plasma

每次开关VPN模式都要调出policykit输入密码，使用体验太差了。

我尝试给nekoray以及两个core设置suid，但nekoray检测到suid就直接退了。

之前使用v2ray的tproxy的时候，可以设置CAP_NET_ADMIN和CAP_NET_BIND_SERVICE，nekoray能不能也用同样的方式让非root用户方便的开关VPN模式。

**建议的必要性**

提升使用体验

**Comment by lonble** [comment]
> 现在 Linux VPN setup 还需运行这段脚本，单独给 core 设置 suid 貌似不能解决问题。
> 
> https://github.com/MatsuriDayo/nekoray/blob/main/res/vpn/vpn-run-root.sh

我看了下这个脚本，内容几乎都是跟macos相关的，与linux有关的只有一条运行nekobox_core。

考虑到目前macos的支持情况，能不能拆分一下，先把linux这边的打包做好。

**Comment by lonble** [comment]
> pre_start_linux 这部分是与 linux 相关的

不是的，你看`start`函数，只有IS_MACOS才会调pre_start_linux。

macos那边我不清楚，但sing-box在linux开启tun不需要那些iptables规则，只需要auto_route=true就行了。

**Comment by lonble** [comment]
> 脚本里面的 fwmark 是 Linux 专用的绕过规则，有点像 Android 的 VPNService ，而 sing-box 本身并没有提供这样的功能。
> 
> 如果你用进程名绕过 core 而不是这种规则，那么效率会降低（参考某些 Windows 用户的错误用法）
> 
> 单纯不使用 pkexec，也是可以的，后面可能会加选项。

如果我没理解错的话，sing-box文档toute里的"auto_detect_interface"就是用来防止回环的。
我理解fwmark是tproxy需要的东西。

**Comment by GuangDai** [comment]
Polkit (PolicyKit) 是一个用于定义系统级策略的框架，它允许不具备某些权限的进程请求这些权限。例如，非 root 用户执行需要超级用户权限的命令。Polkit 与 D-Bus 一同工作，当一个应用程序尝试执行需要特定权限的操作时，Polkit 会询问用户是否批准该操作。

以下是如何使用 Polkit 在 KDE/Linux 上执行特定操作而不需要密码的步骤：

1. **创建 Polkit 规则文件**:

    创建一个新的文件，例如 `/etc/polkit-1/rules.d/10-custom-script.rules`，并在该文件中定义你的策略。下面是一个基本的示例，允许用户 `yourusername` 执行脚本 `/path/to/your/script.sh` 而不需要密码：

    ```javascript
    polkit.addRule(function(action, subject) {
        if (action.id == "org.freedesktop.policykit.exec" &&
            subject.user == "yourusername" &&
            action.lookup("program") == "/path/to/your/script.sh") {
            return polkit.Result.YES;
        }
    });
    ```

2. **使新规则生效**:

    在大多数情况下，你只需保存上述文件，然后 Polkit 就会自动加载新规则。在某些情况下，你可能需要重新启动 Polkit 服务或计算机。

3. **请求权限**:

    当你的应用程序或脚本需要请求权限时，它通常会通过 D-Bus 使用 Polkit。但如果你只是从命令行运行脚本或程序，可以使用 `pkexec` 命令。例如：

    ```bash
    pkexec /path/to/your/script.sh
    ```

    如果你正确设置了上述规则，这将允许 `yourusername` 执行该脚本而不需要输入密码。

**注意**：Polkit 是一个强大的工具，错误的配置可能导致安全问题。始终确保你了解自己在做什么，并且只授予必要的权限。

如果你在 KDE Plasma 桌面上，你可能已经有了一个名为 `polkit-kde-agent` 的组件，它会为 Polkit 提供一个 GUI 提示，让用户选择是否批准某个操作。如果你的系统上没有这个组件，你可能会看到一个不同的提示，或者需要手动安装一个 Polkit 代理，如 `polkit-gnome`。


-----------

我将自己加入了sudoers并且按照这个设置，可以直接启动了
