### ISSUE TITLE
请问如何自行更新sing-box内核版本

### ISSUE THREAD

**Issue by ghost** [MatsuriDayo/nekoray#473]
请问如何自行更新sing-box内核版本

文件夹内没找到可替换文件,尝试改名替换nekobox_core但无效

**Comment by Ezekie1d** [comment]
https://matsuridayo.github.io/n-faq/
![image](https://user-images.githubusercontent.com/56546578/228241160-3689f31f-7acc-45bf-b603-23b5e0114a4e.png)
