### ISSUE TITLE
vpn mode won't work after changing windows!

### ISSUE THREAD

**Issue by AminAlfa** [MatsuriDayo/nekoray#504]
hey I just downgraded from windows 10 to 7 and nekoray was working fine both proxy mode and vpn but after installing windows 7 it wouldn't trigger anything. what should I do?

**Comment by tdjnodj** [comment]
I can use VPN mode in windows7.Please upload your log.

**Comment by AminAlfa** [comment]
> I can use VPN mode in windows7.Please upload your log.

where can I find it?

**Comment by tdjnodj** [comment]
https://matsuridayo.github.io/n-configuration/#vpn-tun

> 在 Windows 系统，由于上游问题，vpn 模式有概率启动失败。如连续多次不能启动，请重启并清理多余的网络接口后再试。

On Windows systems, the vpn mode may fail to start due to upstream issues. If it fails to start several times in a row, please restart and clean up redundant network interfaces and try again.

**Comment by AminAlfa** [comment]
I jusr

> https://matsuridayo.github.io/n-configuration/#vpn-tun
> 
> > 在 Windows 系统，由于上游问题，vpn 模式有概率启动失败。如连续多次不能启动，请重启并清理多余的网络接口后再试。
> 
> On Windows systems, the vpn mode may fail to start due to upstream issues. If it fails to start several times in a row, please restart and clean up redundant network interfaces and try again.

I just installed windows and don't think that's the issue, please tell me where I can find the logs and how can I clean up redundant network.

**Comment by AminAlfa** [comment]
> https://matsuridayo.github.io/n-configuration/#vpn-tun
> 
> > 在 Windows 系统，由于上游问题，vpn 模式有概率启动失败。如连续多次不能启动，请重启并清理多余的网络接口后再试。
> 
> On Windows systems, the vpn mode may fail to start due to upstream issues. If it fails to start several times in a row, please restart and clean up redundant network interfaces and try again.

I just installed windows and don't think that's the issue, please tell me where I can find the logs and how can I clean up redundant network.

**Comment by AminAlfa** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Administrator\Desktop\nekoray>cd path\to\nekoray
The system cannot find the path specified.

C:\Users\Administrator\Desktop\nekoray>path\to\nekoray

C:\Users\Administrator\Desktop\nekoray>nekobox_core run -c config\sing-box-vpn.j
son
2023/04/09 10:54:43 underlyingDNS: {f8eda396-c46e-4143-b7a5-da4ae125cbf5} 5.200.
200.200
sing-box: 1.2-beta5 NekoBox: nekoray-2.19-2023-03-08

←[36mINFO←[0m[0000] router: updated default interface Wireless Network Connectio
n, index 12
←[31mFATAL←[0m[0003] start service: initialize inbound/tun[0]: configure tun int
erface: set ipv4 dns: netsh: exit status 1: "The service has not been started.\n
\n\nThe service has not been started."

C:\Users\Administrator\Desktop\nekoray>

**Comment by AminAlfa** [comment]
am I missing any specific driver for it?

**Comment by tdjnodj** [comment]
May be you are not wrong.Just because win 7 had already not been support :(

**Comment by AminAlfa** [comment]
> May be you are not wrong.Just because win 7 had already not been support :(

wait wtf do you mean? doesn't neckoray support windows 7? then how are you using it? do you know alternative to it so I can tunnel everything(vpn mode)?

**Comment by AminAlfa** [comment]
> I can use VPN mode in windows7.Please upload your log.

please tell me which version are you using.

**Comment by AminAlfa** [comment]
![Uploading image.png…]()

kept spamming and this one stood still for a several seconds.

**Comment by AminAlfa** [comment]
![2](https://user-images.githubusercontent.com/130268588/230776936-f7d41b07-1a63-45ec-9255-58c4d91b84ac.png)

can someone please come and help solve my problem??? what is going on here???

**Comment by AminAlfa** [comment]
this is from v2rayn with cores :

2023-04-09 17:59:46.2068-INFO Tun mode configuration file test start
2023-04-09 17:59:46.6769-DEBUG +0330 2023-04-09 17:59:46 [36mINFO[0m router: loaded geosite database: 1329 codes
+0330 2023-04-09 17:59:46 [36mINFO[0m router: updated default interface Wireless Network Connection, index 12
[31mFATAL[0m[0000] start service: initialize inbound/tun[tun-in]: configure tun interface: There are no child processes to wait for.
,+0330 2023-04-09 17:59:46 [36mINFO[0m router: loaded geosite database: 1329 codes
+0330 2023-04-09 17:59:46 [36mINFO[0m router: updated default interface Wireless Network Connection, index 12
[31mFATAL[0m[0000] start service: initialize inbound/tun[tun-in]: configure tun interface: There are no child processes to wait for.

2023-04-09 17:59:46.6769-DEBUG    at v2rayN.Base.TunHandler.CoreStartTest()
2023-04-09 17:59:46.6769-INFO Tun mode configuration file test end
2023-04-09 17:59:47.1519-DEBUG start tun mode fail,start tun mode fail
2023-04-09 17:59:47.1519-DEBUG    at v2rayN.Base.TunHandler.CoreStart()
2023-04-09 17:59:55.2349-DEBUG The operation has timed out.,The operation has timed out.
2023-04-09 17:59:55.2349-DEBUG    at System.Net.HttpWebRequest.GetResponse()
   at v2rayN.Handler.DownloadHandle.GetRealPingTime(String url, IWebProxy webProxy, Int32 downloadTimeout, Int32& responseTime)
2023-04-09 17:59:56.9552-DEBUG start tun mode fail,start tun mode fail
2023-04-09 17:59:56.9552-DEBUG    at v2rayN.Base.TunHandler.CoreStart()
2023-04-09 17:59:56.9552-INFO Tun mode monitors restart
2023-04-09 18:00:06.9859-DEBUG start tun mode fail,start tun mode fail
2023-04-09 18:00:06.9859-DEBUG    at v2rayN.Base.TunHandler.CoreStart()
2023-04-09 18:00:06.9859-INFO Tun mode monitors restart

**Comment by AminAlfa** [comment]
![3](https://user-images.githubusercontent.com/130268588/230784028-a75fea4c-256c-45c2-a2db-a9f6ef7ecd12.png)

**Comment by AminAlfa** [comment]
![4](https://user-images.githubusercontent.com/130268588/230989930-72a550d1-6e6e-4d89-b6cb-592888654333.png)
![5](https://user-images.githubusercontent.com/130268588/230989945-31a1fe3e-e473-41c6-a0a6-5a8d1c9dfa9f.png)
So IDK which one of the services was preventing it after I set them to automatic but now something else came up even after being able to check vpn mode and that is what you can see in the pictures. can't use it but I see the up and down internet traffic.

**Comment by AminAlfa** [comment]
N A
←[36mINFO←[0m[0002] outbound/direct[direct]: outbound packet connection to 5.200
.200.200:53
←[37mDEBUG←[0m[0002] [←[38;5;34m1478053609←[0m] dns: exchanged mcix.ircf.space N
OERROR 600
←[36mINFO←[0m[0002] [←[38;5;34m1478053609←[0m] dns: exchanged mcix.ircf.space A
mcix.ircf.space. 36 IN A 170.114.45.45
←[36mINFO←[0m[0002] [←[38;5;34m1478053609←[0m] dns: exchanged mcix.ircf.space A
mcix.ircf.space. 36 IN A 170.114.45.250
←[36mINFO←[0m[0002] [←[38;5;34m1478053609←[0m] dns: exchanged mcix.ircf.space A
mcix.ircf.space. 36 IN A 170.114.45.2
←[36mINFO←[0m[0002] [←[38;5;34m1478053609←[0m] dns: exchanged mcix.ircf.space A
mcix.ircf.space. 36 IN A 170.114.46.51
←[36mINFO←[0m[0002] [←[38;5;34m1478053609←[0m] dns: exchanged mcix.ircf.space OP
T OPT PSEUDOSECTION: EDNS: version 0 flags: udp: 512
←[36mINFO←[0m[0002] [←[38;5;34m1478053609←[0m] dns: exchanged mcix.ircf.space. A
 mcix.ircf.space. 36 IN A 170.114.45.45
←[36mINFO←[0m[0002] [←[38;5;34m1478053609←[0m] dns: exchanged mcix.ircf.space. A
 mcix.ircf.space. 36 IN A 170.114.45.250
←[36mINFO←[0m[0002] [←[38;5;34m1478053609←[0m] dns: exchanged mcix.ircf.space. A
 mcix.ircf.space. 36 IN A 170.114.45.2
←[36mINFO←[0m[0002] [←[38;5;34m1478053609←[0m] dns: exchanged mcix.ircf.space. A
 mcix.ircf.space. 36 IN A 170.114.46.51
←[36mINFO←[0m[0002] [←[38;5;168m1261242776←[0m] inbound/tun[0]: inbound packet c
onnection from [fdfe:dcba:9876::1]:52254
←[36mINFO←[0m[0002] [←[38;5;168m1261242776←[0m] inbound/tun[0]: inbound packet c
onnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0002] [←[38;5;168m1261242776←[0m] router: found process path: \Dev
ice\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0002] [←[38;5;168m1261242776←[0m] outbound/socks[nekoray-socks]: o
utbound packet connection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0002] [←[38;5;28m4012153100←[0m] inbound/tun[0]: inbound packet co
nnection from [fdfe:dcba:9876::1]:52256
←[36mINFO←[0m[0002] [←[38;5;28m4012153100←[0m] inbound/tun[0]: inbound packet co
nnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0002] [←[38;5;28m4012153100←[0m] router: found process path: \Devi
ce\HarddiskVolume1\Users\Administrator\Desktop\nekoray\nekoray_core.exe
←[37mDEBUG←[0m[0002] [←[38;5;28m4012153100←[0m] router: match[4] port=53 process
_name=[nekoray_core nekoray_core.exe] => dns-out
←[37mDEBUG←[0m[0002] [←[38;5;28m4012153100←[0m] dns: exchange mcix.ircf.space. I
N AAAA
←[37mDEBUG←[0m[0002] [←[38;5;28m4012153100←[0m] dns: exchanged mcix.ircf.space N
OERROR 600
←[36mINFO←[0m[0002] [←[38;5;28m4012153100←[0m] dns: exchanged mcix.ircf.space SO
A ircf.space. 414 IN SOA alex.ns.cloudflare.com. dns.cloudflare.com. 2306637115
10000 2400 604800 3600
←[36mINFO←[0m[0002] [←[38;5;28m4012153100←[0m] dns: exchanged mcix.ircf.space OP
T OPT PSEUDOSECTION: EDNS: version 0 flags: udp: 512
←[36mINFO←[0m[0004] [←[38;5;227m2481172187←[0m] inbound/tun[0]: inbound packet c
onnection from 172.19.0.1:137
←[36mINFO←[0m[0004] [←[38;5;227m2481172187←[0m] inbound/tun[0]: inbound packet c
onnection to 172.19.0.15:137
←[36mINFO←[0m[0004] [←[38;5;227m2481172187←[0m] router: found process path: :Sys
tem
←[37mDEBUG←[0m[0004] [←[38;5;227m2481172187←[0m] router: match[1] network=udp po
rt=[135 137 138 139 5353] => block
←[36mINFO←[0m[0004] [←[38;5;227m2481172187←[0m] outbound/block[block]: blocked p
acket connection to 172.19.0.15:137
←[36mINFO←[0m[0004] [←[38;5;151m855789447←[0m] inbound/tun[0]: inbound packet co
nnection from [fdfe:dcba:9876::1]:58804
←[36mINFO←[0m[0004] [←[38;5;151m855789447←[0m] inbound/tun[0]: inbound packet co
nnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0004] [←[38;5;151m855789447←[0m] router: found process path: \Devi
ce\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0004] [←[38;5;151m855789447←[0m] outbound/socks[nekoray-socks]: ou
tbound packet connection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] inbound/tun[0]: inbound packet co
nnection from [fdfe:dcba:9876::1]:58806
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] inbound/tun[0]: inbound packet co
nnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] router: found process path: \Devi
ce\HarddiskVolume1\Users\Administrator\Desktop\nekoray\nekoray_core.exe
←[37mDEBUG←[0m[0004] [←[38;5;51m3372973236←[0m] router: match[4] port=53 process
_name=[nekoray_core nekoray_core.exe] => dns-out
←[37mDEBUG←[0m[0004] [←[38;5;51m3372973236←[0m] dns: exchange mcix.ircf.space. I
N A
←[37mDEBUG←[0m[0004] [←[38;5;51m3372973236←[0m] dns: cached mcix.ircf.space NOER
ROR 597
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] dns: cached mcix.ircf.space A mci
x.ircf.space. 597 IN A 170.114.45.45
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] dns: cached mcix.ircf.space A mci
x.ircf.space. 597 IN A 170.114.45.250
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] dns: cached mcix.ircf.space A mci
x.ircf.space. 597 IN A 170.114.45.2
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] dns: cached mcix.ircf.space A mci
x.ircf.space. 597 IN A 170.114.46.51
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] dns: cached mcix.ircf.space OPT O
PT PSEUDOSECTION: EDNS: version 0 flags: udp: 512
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] dns: exchanged mcix.ircf.space. A
 mcix.ircf.space. 597 IN A 170.114.45.45
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] dns: exchanged mcix.ircf.space. A
 mcix.ircf.space. 597 IN A 170.114.45.250
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] dns: exchanged mcix.ircf.space. A
 mcix.ircf.space. 597 IN A 170.114.45.2
←[36mINFO←[0m[0004] [←[38;5;51m3372973236←[0m] dns: exchanged mcix.ircf.space. A
 mcix.ircf.space. 597 IN A 170.114.46.51
←[36mINFO←[0m[0004] [←[38;5;222m2283965705←[0m] inbound/tun[0]: inbound packet c
onnection from [fdfe:dcba:9876::1]:65511
←[36mINFO←[0m[0004] [←[38;5;222m2283965705←[0m] inbound/tun[0]: inbound packet c
onnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0004] [←[38;5;222m2283965705←[0m] router: found process path: \Dev
ice\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0004] [←[38;5;222m2283965705←[0m] outbound/socks[nekoray-socks]: o
utbound packet connection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0004] [←[38;5;143m771636351←[0m] inbound/tun[0]: inbound packet co
nnection from [fdfe:dcba:9876::1]:65513
←[36mINFO←[0m[0004] [←[38;5;143m771636351←[0m] inbound/tun[0]: inbound packet co
nnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0004] [←[38;5;143m771636351←[0m] router: found process path: \Devi
ce\HarddiskVolume1\Users\Administrator\Desktop\nekoray\nekoray_core.exe
←[37mDEBUG←[0m[0004] [←[38;5;143m771636351←[0m] router: match[4] port=53 process
_name=[nekoray_core nekoray_core.exe] => dns-out
←[37mDEBUG←[0m[0004] [←[38;5;143m771636351←[0m] dns: exchange mcix.ircf.space. I
N AAAA
←[37mDEBUG←[0m[0004] [←[38;5;143m771636351←[0m] dns: cached mcix.ircf.space NOER
ROR 597
←[36mINFO←[0m[0004] [←[38;5;143m771636351←[0m] dns: cached mcix.ircf.space SOA i
rcf.space. 597 IN SOA alex.ns.cloudflare.com. dns.cloudflare.com. 2306637115 100
00 2400 604800 3600
←[36mINFO←[0m[0004] [←[38;5;143m771636351←[0m] dns: cached mcix.ircf.space OPT O
PT PSEUDOSECTION: EDNS: version 0 flags: udp: 512
←[36mINFO←[0m[0005] [←[38;5;39m3658271726←[0m] inbound/tun[0]: inbound packet co
nnection from 172.19.0.1:137
←[36mINFO←[0m[0005] [←[38;5;39m3658271726←[0m] inbound/tun[0]: inbound packet co
nnection to 172.19.0.15:137
←[36mINFO←[0m[0005] [←[38;5;39m3658271726←[0m] router: found process path: :Syst
em
←[37mDEBUG←[0m[0005] [←[38;5;39m3658271726←[0m] router: match[1] network=udp por
t=[135 137 138 139 5353] => block
←[36mINFO←[0m[0005] [←[38;5;39m3658271726←[0m] outbound/block[block]: blocked pa
cket connection to 172.19.0.15:137
←[36mINFO←[0m[0005] [←[38;5;206m3802661310←[0m] inbound/tun[0]: inbound packet c
onnection from [fdfe:dcba:9876::1]:65297
←[36mINFO←[0m[0005] [←[38;5;206m3802661310←[0m] inbound/tun[0]: inbound packet c
onnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0005] [←[38;5;206m3802661310←[0m] router: found process path: \Dev
ice\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0005] [←[38;5;206m3802661310←[0m] outbound/socks[nekoray-socks]: o
utbound packet connection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0005] [←[38;5;158m1362522510←[0m] inbound/tun[0]: inbound packet c
onnection from 172.19.0.1:137
←[36mINFO←[0m[0005] [←[38;5;158m1362522510←[0m] inbound/tun[0]: inbound packet c
onnection to 172.19.0.15:137
←[36mINFO←[0m[0005] [←[38;5;158m1362522510←[0m] router: found process path: :Sys
tem
←[37mDEBUG←[0m[0005] [←[38;5;158m1362522510←[0m] router: match[1] network=udp po
rt=[135 137 138 139 5353] => block
←[36mINFO←[0m[0005] [←[38;5;158m1362522510←[0m] outbound/block[block]: blocked p
acket connection to 172.19.0.15:137
←[36mINFO←[0m[0006] [←[38;5;210m3031566018←[0m] inbound/tun[0]: inbound packet c
onnection from 172.19.0.1:59190
←[36mINFO←[0m[0006] [←[38;5;210m3031566018←[0m] inbound/tun[0]: inbound packet c
onnection to 172.19.0.2:53
←[36mINFO←[0m[0006] [←[38;5;210m3031566018←[0m] router: found process path: \Dev
ice\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0006] [←[38;5;210m3031566018←[0m] outbound/socks[nekoray-socks]: o
utbound packet connection to 172.19.0.2:53
←[36mINFO←[0m[0006] [←[38;5;153m1239561550←[0m] inbound/tun[0]: inbound packet c
onnection from 172.19.0.1:137
←[36mINFO←[0m[0006] [←[38;5;153m1239561550←[0m] inbound/tun[0]: inbound packet c
onnection to 172.19.0.15:137
←[36mINFO←[0m[0006] [←[38;5;153m1239561550←[0m] router: found process path: :Sys
tem
←[37mDEBUG←[0m[0006] [←[38;5;153m1239561550←[0m] router: match[1] network=udp po
rt=[135 137 138 139 5353] => block
←[36mINFO←[0m[0006] [←[38;5;153m1239561550←[0m] outbound/block[block]: blocked p
acket connection to 172.19.0.15:137
←[37mDEBUG←[0m[0012] [←[38;5;34m1478053609←[0m] inbound/tun[0]: connection close
d: io: read/write on closed pipe | upstream: context canceled
←[37mDEBUG←[0m[0012] [←[38;5;28m4012153100←[0m] inbound/tun[0]: connection close
d: io: read/write on closed pipe | upstream: context canceled
←[36mINFO←[0m[0014] [←[38;5;83m2130907284←[0m] inbound/tun[0]: inbound packet co
nnection from [fdfe:dcba:9876::1]:53658
←[36mINFO←[0m[0014] [←[38;5;83m2130907284←[0m] inbound/tun[0]: inbound packet co
nnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0014] [←[38;5;83m2130907284←[0m] router: found process path: \Devi
ce\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0014] [←[38;5;83m2130907284←[0m] outbound/socks[nekoray-socks]: ou
tbound packet connection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0014] [←[38;5;225m1598709981←[0m] inbound/tun[0]: inbound packet c
onnection from [fdfe:dcba:9876::1]:62781
←[36mINFO←[0m[0014] [←[38;5;225m1598709981←[0m] inbound/tun[0]: inbound packet c
onnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0014] [←[38;5;225m1598709981←[0m] router: found process path: \Dev
ice\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0014] [←[38;5;225m1598709981←[0m] outbound/socks[nekoray-socks]: o
utbound packet connection to [fdfe:dcba:9876::2]:53
←[37mDEBUG←[0m[0014] [←[38;5;51m3372973236←[0m] inbound/tun[0]: connection close
d: io: read/write on closed pipe | upstream: context canceled
←[37mDEBUG←[0m[0014] [←[38;5;143m771636351←[0m] inbound/tun[0]: connection close
d: io: read/write on closed pipe | upstream: context canceled
←[36mINFO←[0m[0015] [←[38;5;212m2381096388←[0m] inbound/tun[0]: inbound packet c
onnection from 172.19.0.1:62718
←[36mINFO←[0m[0015] [←[38;5;212m2381096388←[0m] inbound/tun[0]: inbound packet c
onnection to 172.19.0.2:53
←[36mINFO←[0m[0015] [←[38;5;212m2381096388←[0m] router: found process path: \Dev
ice\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0015] [←[38;5;212m2381096388←[0m] outbound/socks[nekoray-socks]: o
utbound packet connection to 172.19.0.2:53
←[36mINFO←[0m[0015] [←[38;5;188m3446158379←[0m] inbound/tun[0]: inbound packet c
onnection from 172.19.0.1:55026
←[36mINFO←[0m[0016] [←[38;5;188m3446158379←[0m] inbound/tun[0]: inbound packet c
onnection to 172.19.0.2:53
←[36mINFO←[0m[0016] [←[38;5;188m3446158379←[0m] router: found process path: \Dev
ice\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0016] [←[38;5;188m3446158379←[0m] outbound/socks[nekoray-socks]: o
utbound packet connection to 172.19.0.2:53
←[36mINFO←[0m[0017] [←[38;5;193m192031409←[0m] inbound/tun[0]: inbound packet co
nnection from 172.19.0.1:137
←[36mINFO←[0m[0017] [←[38;5;193m192031409←[0m] inbound/tun[0]: inbound packet co
nnection to 172.19.0.15:137
←[36mINFO←[0m[0017] [←[38;5;193m192031409←[0m] router: found process path: :Syst
em
←[37mDEBUG←[0m[0017] [←[38;5;193m192031409←[0m] router: match[1] network=udp por
t=[135 137 138 139 5353] => block
←[36mINFO←[0m[0017] [←[38;5;193m192031409←[0m] outbound/block[block]: blocked pa
cket connection to 172.19.0.15:137
←[36mINFO←[0m[0018] [←[38;5;156m750042699←[0m] inbound/tun[0]: inbound packet co
nnection from 172.19.0.1:137
←[36mINFO←[0m[0018] [←[38;5;156m750042699←[0m] inbound/tun[0]: inbound packet co
nnection to 172.19.0.15:137
←[36mINFO←[0m[0018] [←[38;5;156m750042699←[0m] router: found process path: :Syst
em
←[37mDEBUG←[0m[0018] [←[38;5;156m750042699←[0m] router: match[1] network=udp por
t=[135 137 138 139 5353] => block
←[36mINFO←[0m[0018] [←[38;5;156m750042699←[0m] outbound/block[block]: blocked pa
cket connection to 172.19.0.15:137
←[36mINFO←[0m[0019] [←[38;5;121m1958087785←[0m] inbound/tun[0]: inbound packet c
onnection from 172.19.0.1:137
←[36mINFO←[0m[0019] [←[38;5;121m1958087785←[0m] inbound/tun[0]: inbound packet c
onnection to 172.19.0.15:137
←[36mINFO←[0m[0019] [←[38;5;121m1958087785←[0m] router: found process path: :Sys
tem
←[37mDEBUG←[0m[0019] [←[38;5;121m1958087785←[0m] router: match[1] network=udp po
rt=[135 137 138 139 5353] => block
←[36mINFO←[0m[0019] [←[38;5;121m1958087785←[0m] outbound/block[block]: blocked p
acket connection to 172.19.0.15:137
←[36mINFO←[0m[0019] [←[38;5;191m2274633215←[0m] inbound/tun[0]: inbound packet c
onnection from [fdfe:dcba:9876::1]:60849
←[36mINFO←[0m[0019] [←[38;5;191m2274633215←[0m] inbound/tun[0]: inbound packet c
onnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0019] [←[38;5;191m2274633215←[0m] router: found process path: \Dev
ice\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0019] [←[38;5;191m2274633215←[0m] outbound/socks[nekoray-socks]: o
utbound packet connection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0020] [←[38;5;192m143058352←[0m] inbound/tun[0]: inbound packet co
nnection from 172.19.0.1:56591
←[36mINFO←[0m[0020] [←[38;5;192m143058352←[0m] inbound/tun[0]: inbound packet co
nnection to 172.19.0.2:53
←[36mINFO←[0m[0020] [←[38;5;192m143058352←[0m] router: found process path: \Devi
ce\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0020] [←[38;5;192m143058352←[0m] outbound/socks[nekoray-socks]: ou
tbound packet connection to 172.19.0.2:53
←[36mINFO←[0m[0026] [←[38;5;226m3374512338←[0m] inbound/tun[0]: inbound packet c
onnection from 172.19.0.1:54933
←[36mINFO←[0m[0026] [←[38;5;226m3374512338←[0m] inbound/tun[0]: inbound packet c
onnection to 172.19.0.2:53
←[36mINFO←[0m[0026] [←[38;5;226m3374512338←[0m] router: found process path: \Dev
ice\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0026] [←[38;5;226m3374512338←[0m] outbound/socks[nekoray-socks]: o
utbound packet connection to 172.19.0.2:53
←[36mINFO←[0m[0027] [←[38;5;33m1224857361←[0m] inbound/tun[0]: inbound packet co
nnection from [fdfe:dcba:9876::1]:55035
←[36mINFO←[0m[0027] [←[38;5;33m1224857361←[0m] inbound/tun[0]: inbound packet co
nnection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0027] [←[38;5;33m1224857361←[0m] router: found process path: \Devi
ce\HarddiskVolume1\Windows\System32\svchost.exe
←[36mINFO←[0m[0027] [←[38;5;33m1224857361←[0m] outbound/socks[nekoray-socks]: ou
tbound packet connection to [fdfe:dcba:9876::2]:53
←[36mINFO←[0m[0032] [←[38;5;33m2786264337←[0m] inbound/tun[0]: inbound packet co
nnection from 172.19.0.1:137
←[36mINFO←[0m[0032] [←[38;5;33m2786264337←[0m] inbound/tun[0]: inbound packet co
nnection to 172.19.0.15:137
←[36mINFO←[0m[0032] [←[38;5;33m2786264337←[0m] router: found process path: :Syst
em
←[37mDEBUG←[0m[0032] [←[38;5;33m2786264337←[0m] router: match[1] network=udp por
t=[135 137 138 139 5353] => block
←[36mINFO←[0m[0032] [←[38;5;33m2786264337←[0m] outbound/block[block]: blocked pa
cket connection to 172.19.0.15:137
←[36mINFO←[0m[0033] [←[38;5;194m2913804722←[0m] inbound/tun[0]: inbound packet c
onnection from 172.19.0.1:137
←[36mINFO←[0m[0033] [←[38;5;194m2913804722←[0m] inbound/tun[0]: inbound packet c
onnection to 172.19.0.15:137
←[36mINFO←[0m[0033] [←[38;5;194m2913804722←[0m] router: found process path: :Sys
tem
←[37mDEBUG←[0m[0033] [←[38;5;194m2913804722←[0m] router: match[1] network=udp po
rt=[135 137 138 139 5353] => block
←[36mINFO←[0m[0033] [←[38;5;194m2913804722←[0m] outbound/block[block]: blocked p
acket connection to 172.19.0.15:137
←[36mINFO←[0m[0033] [←[38;5;226m3697679836←[0m] inbound/tun[0]: inbound packet c
onnection from 172.19.0.1:137
←[36mINFO←[0m[0033] [←[38;5;226m3697679836←[0m] inbound/tun[0]: inbound packet c
onnection to 172.19.0.15:137
←[36mINFO←[0m[0033] [←[38;5;226m3697679836←[0m] router: found process path: :Sys
tem
←[37mDEBUG←[0m[0033] [←[38;5;226m3697679836←[0m] router: match[1] network=udp po
rt=[135 137 138 139 5353] => block
←[36mINFO←[0m[0033] [←[38;5;226m3697679836←[0m] outbound/block[block]: blocked p
acket connection to 172.19.0.15:137
