### ISSUE TITLE
[wayland]点击托盘图标或右键菜单显示主窗口后无法自动显示在桌面，需要手动切换

### ISSUE THREAD

**Issue by Bryan2333** [MatsuriDayo/nekoray#527]
**描述问题**

预期行为：不需要手动切换

实际行为：点击托盘图标或右键菜单显示主窗口后无法自动显示在桌面，需要使用Alt-tab来手动切换窗口

**如何复现**

我用的是Arch Linux, DE是Gnome 43.4

**日志**

录屏

https://user-images.githubusercontent.com/31512600/232359291-9601d761-0186-4757-9c86-77ac3311c3f9.mp4

**Comment by Bryan2333** [comment]
没有，就只有一个笔记本内屏。

**Comment by Bryan2333** [comment]
没用，刚刚是了一下，用这个包提供的nekoray依然存在这个问题。

**Comment by Bryan2333** [comment]
我用 journalctl 看了一下日志，好像跟这个有关
```
4月 17 11:36:22 Bryan-YOGA14s nekoray[38057]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
4月 17 11:36:22 Bryan-YOGA14s nekoray[38057]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

**Comment by zhullyb** [comment]
可以试试 AUR/nekoray ，我今天刚更新到 qt6 ，在 kde wayland 环境下已经没有这个问题了

**Comment by Bryan2333** [comment]
我现在已经转去用Hyprland了，不用Gnome了，没法测试。

**Comment by Bryan2333** [comment]
> 可以试试 AUR/nekoray ，我今天刚更新到 qt6 ，在 kde wayland 环境下已经没有这个问题了

确实是没这个问题了。
