### ISSUE TITLE
Requesting subscription 11 error: SSL handshake failed

### ISSUE THREAD

**Issue by xmohammad1** [MatsuriDayo/nekoray#535]
hey , im using windows 10 , my domain and configs are using 1.3 TLS
when i want to update my subcription i get this error
<<<<<<<< Requesting subscription Mine error: SSL handshake failed
i checked Ignor TLS errors when updating subscription , but didnt worked
how may i fix it? or is it possible to fix it in next version?

**Comment by xmohammad1** [comment]
any one can help?

**Comment by GamerHard77** [comment]
I have the same problem.
Please someone help.
