### ISSUE TITLE
Please add reality support

### ISSUE THREAD

**Issue by Alixkiller** [MatsuriDayo/nekoray#546]
so far i could not get connected to v2ray with reality , 1 month already passed since the option added into v2ray , can you please make nekoray support reality ?

**Comment by tdjisdj** [comment]
Please use nekobox

**Comment by Alixkiller** [comment]
> Please use nekobox

how?

**Comment by Alixkiller** [comment]
> @Alixkillertdjisdj means to let you switch the core to sing-box in the basic configuration, then select manual input configuration, then select custom (sing-box outbound), and then paste the json format of the reality configuration of sing-box to the configuration box, so that it can support the reality protocol

i know its a bother , but can you please explain specifically and a little easier for me to understand? i would really really appreciate it . thanks

**Comment by Alixkiller** [comment]
nvm , i found a solution in here https://github.com/SasukeFreestyle/XTLS-Iran-Reality

**Comment by guan9527b** [comment]
The new version can already support reality, scan the code to add it directly
