### ISSUE TITLE
sing-box 内核

### ISSUE THREAD

**Issue by arm64v8a** [MatsuriDayo/nekoray#58]
1.10版本加入，目前上游项目和neko支持还不完善，已知问题稍后补充。

**Comment by laincat** [comment]
不能改名直接替换新内核？

**Comment by z10056** [comment]
> sing-box dev-next 2022/09/29
> 
> 优点
> 
> 1. 支持 ssh wireguard 等代理类型（非热门，GUI暂未适配）
> 2. 支持 shadowsocks 2022 cipher
> 3. 内置 hysteria 出站
> 4. 支持 Mixed 入站
> 5. 更丰富灵活的路由规则（GUI暂时保留使用v2ray的语法，需要sing-box语法的可以用“自定义”）
> 
> 功能缺失 ~1. 上游未提供流量统计接口 (类似v2ray StatsService)~ 已支持 2. 未适配连接统计 3. 设计上只允许部分类型的出站使用 streamSettings / transport 4. 设计上没有 FakeDNS
> 
> 上游BUG
> 
> 1. ~未实现 Shadowsocks obfs-local ，无法使用此类型服务器。~
> 2. ~Socks 出站 AsIs 未正确实现，仍需查询DNS，增加延迟。~
> 
> 更多问题欢迎反馈，需要提供完整的日志信息。

求作者大大GUI支持"wireguard
