### ISSUE TITLE
Error when connecting with Reality protocol: uTLS is required by reality client

### ISSUE THREAD

**Issue by Matin-B** [MatsuriDayo/nekoray#580]
I'm encountering an issue while trying to connect using the Reality protocol in the Nekoray client on Linux. I have configured the program's core to use the sing-box backend in order to utilize the Reality protocol. However, when attempting to connect to the configured server, I receive the following error message: "create service: parse outbound[0]: uTLS is required by reality client".

I have tested the configuration on my mobile device using the V2rayNG client, and it works without any issues. This indicates that the configuration itself is correct and the problem is not originating from there.

It seems that the Nekoray client specifically requires uTLS for the Reality protocol, but I might be missing some additional configuration or dependencies on the Linux platform. Could you please provide guidance on how to properly set up uTLS for the Reality protocol in the Nekoray client on Linux?

**Comment by Matin-B** [comment]
I have found a solution now:

We need to go to the configuration edit section through V2RayNG and find out which option the TLS Fingerprint is set to. Then, we need to edit the configuration in Nekoray and set uTLS equal to the TLS Fingerprint configuration.

Thanks to [Amir19098](https://t.me/Amir19098) in [Nekoray group](https://t.me/nekoray_group)

**Comment by matinabbasi** [comment]
hello matin
