### ISSUE TITLE
订阅地址 错误: SSL 握手失败   订阅地址已在下方贴出  

### ISSUE THREAD

**Issue by chen1376** [MatsuriDayo/nekoray#581]
>>>>>>>> 正在请求订阅: https://hk.ch1376.love:8888/api/auth/subscribe/Qkx2d3Z4dDB0c2VMRzhicV9EanFUY2xJem11QmVNTXR6NC0tc2lDQ3hZRzMzSExG
<<<<<<<< 请求订阅 https://hk.ch1376.love:8888/api/auth/subscribe/Qkx2d3Z4dDB0c2VMRzhicV9EanFUY2xJem11QmVNTXR6NC0tc2lDQ3hZRzMzSExG 错误: SSL 握手失败

请问这是我订阅地址的问题吗  此订阅地址在NekoBox可以正常使用

**Comment by tdjnodj** [comment]
建议直接发到作者的邮箱里：nekoha_matsuri@protonmail.com

试下 基本设置 -> 订阅 -> 更新订阅时忽略 TLS 错误

**Comment by chen1376** [comment]
> 

谢谢，设置过基本设置 -> 订阅 -> 更新订阅时忽略 TLS 错误   还是提示 才来发的问题

**Comment by tdjnodj** [comment]
虽然我不知道怎么解决，但强烈建议你赶紧隐藏订阅地址

**Comment by chen1376** [comment]
> 

谢谢提醒，订阅链接是我自己搭建的，随时可以关闭

**Comment by chen1376** [comment]
这个版本 可以，谢谢大佬更新！





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MatsuriDayo/nekoray"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月14日(星期天) 下午4:14
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [MatsuriDayo/nekoray] 订阅地址 错误: SSL 握手失败   订阅地址已在下方贴出   (Issue #581)





 
https://github.com/MatsuriDayo/nekoray/releases/tag/3.0 下载此版测试
