### ISSUE TITLE
请教关于“?ed=2048”这个参数设置的问题

### ISSUE THREAD

**Issue by egg1234** [MatsuriDayo/nekoray#631]
在vmess/vless的websocket设置里面，有EarlyData Length及EarlyData Name这两个小框，对应的“?ed=2048”这个参数应该怎样填到这两个小框里面呢

谢谢！

**Comment by tdjisdj** [comment]
nekoray 支持将 `?ed=2048` 参数自动转换。

如果你就是喜欢写 ws Early Data。那么 `EarlyData Name` 填写 `Sec-Protocol-Websocket`

**Comment by tdjisdj** [comment]
nekoray 支持将 `?ed=2048` 参数自动转换。

如果你就是喜欢写 ws Early Data。那么 `EarlyData Name` 填写 `Sec-Protocol-Websocket`
