### ISSUE TITLE
使用Hysteria://导入后启动提示找不到hysteria核心

### ISSUE THREAD

**Issue by evanfury** [MatsuriDayo/nekoray#642]
**描述问题**

预期行为：正常使用

实际行为：找不到核心

**如何复现**
客户端已经切换到sing-box核心
使用hi hysteria配置服务，复制hysteria://链接，选择使用剪贴板导入，右键启动，提示找不到hysteria核心
hysteria://example.coom:28459?protocol=wechat-video&auth=FFltVYSMvsmvDulL28rgJBUn058CjjX8RXDkX43blIaQ9i06iu&obfsParam=&peer=example.coom&insecure=0&upmbps=55&downmbps=110&alpn=h3#Hys-RU

![123](https://github.com/MatsuriDayo/nekoray/assets/53717843/02ce3eed-1805-4cda-9d99-0f9c7d847e04)

提供有帮助的截图，录像，文字说明，订阅链接等。

**日志**

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by StarDust2608** [comment]
没法下，不知道为什么找不到
