### ISSUE TITLE
How to use PiHole as my dns in NekoRay?

### ISSUE THREAD

**Issue by pato-pan** [MatsuriDayo/nekoray#718]
Pi-Hole is a dns resolver inside my network. I attempted to make NekoRay use Pi-Hole by going to it's routing options, dns, and replacing the remote dns from 8.8.8.8 to my pi-hole's internal ip address (192.168.2.15). I use NekoRay to connect to an http TinyProxy on another router in my network (192.168.1.1)

When I do this, the requests are successfully sent to Pi-Hole and Pi-Hole successfully resolves them, but NekoRay's logs say "no route to host" and I have no internet connection. To solve this problem I tried to replicate the configuration shown here https://github.com/v2fly/v2ray-core/discussions/2223 to the best of my ability, but I was stuck at 

> "tag": "tag_of_your_primary_proxy_outbound"

I can't find a tag in my configuration that should work here, and the file for the http profile shows no tags. I think the circumstances are very different because different protocols and programs were being used. How can I achieve this? I should mention I am on a virtual machine.

Is it possible to simply use the system dns, instead of configuring it in the application?

Edit: I forgot to say, I am using system proxy and tun. This could be important information. I am not sure on what system proxy does, I probably don't need it.

**Comment by xchacha20-ietf-poly1305** [comment]
#664
