### ISSUE TITLE
[Bug] Unable to connect after switching nodes when using TUN and FakeDNS

### ISSUE THREAD

**Issue by cc826f2f** [MatsuriDayo/nekoray#722]
Problem: Unable to connect after switching nodes when using TUN and FakeDNS

Core: sing-box

TUN: Enabled IPv6 and Strict Route

DNS Object:

```
{
    "fakeip": {
        "enabled": true,
        "inet4_range": "198.18.0.0/15",
        "inet6_range": "fc00::/18"
    },
    "rules": [
        {
            "disable_cache": true,
            "geosite": [
                "cn"
            ],
            "server": "local"
        },
        {
            "disable_cache": true,
            "geosite": [
                "category-ads-all"
            ],
            "server": "block"
        }
    ],
    "servers": [
        {
            "address": "fakeip",
            "detour": "proxy",
            "tag": "fakedns"
        },
        {
            "address": "223.5.5.5",
            "detour": "direct",
            "tag": "local"
        },
        {
            "address": "rcode://success",
            "tag": "block"
        }
    ]
}
```

**Comment by cc826f2f** [comment]
> Have you tried clearing the dns cache? Also, please provide the full log.

I know it's caused by DNS cache, but it works well on v2rayN, so maybe we can add an option to clean DNS cache after switching nodes? I think it's better.

**Comment by cc826f2f** [comment]
> Flush DNS Cache has been realized(in sing-box), but I don't know why it doesn't work.
> 
> Make sure you have enabled `Internal Tun`

Well, thanks for your help

**Comment by gharajedaghi** [comment]
> Flush DNS Cache has been realized(in sing-box), but I don't know why it doesn't work.
> 
> Make sure you have enabled `Internal Tun`



> Have you tried clearing the dns cache? Also, please provide the full log.
https://copyprogramming.com/howto/how-to-clear-dns-cache-in-22-04
