### ISSUE TITLE
Asking HTTP/3 with Quic support

### ISSUE THREAD

**Issue by MrSaeid007** [MatsuriDayo/nekoray#724]
Dear @arm64v8a @SafaSafari @TheWeirdDev 

I wanted to ask if the Nekoray app support for HTTP/3 with the Quic support function.

Recently, I see this option in x-ui panel(picture below) 

![QuicHTTP3](https://github.com/MatsuriDayo/nekoray/assets/69323214/ff630de7-de4c-4187-8c7e-b8c696ce421d)

I was wondering if we can use or force the app to establish HTTP/3 with Quic connection to our server (Reality or CDN).
Does Nekoray App support HTTP/3 with Quic?

Thank you.

**Comment by xchacha20-ietf-poly1305** [comment]
You can use quic with other protocol in nekoray.

But REALITY does not support http/3.

In your image, "quic" is for sniffing, not the transport.

**Comment by MrSaeid007** [comment]
> You can use quic with other protocol in nekoray.
> 
> But REALITY does not support http/3.
> 
> In your image, "quic" is for sniffing, not the transport.

Thanks.
