### ISSUE TITLE
Shadowsocks服务器中的v2ray-plugin插件可能未能正确工作

### ISSUE THREAD

**Issue by chenshaoju** [MatsuriDayo/nekoray#753]
**描述问题**

预期行为：Shadowsocks模式下的v2ray-plugin插件正常工作。

实际行为：无法正常工作。

服务器系统：Debian
客户端系统：Windows 10
客户端nekoray版本：3.12

**如何复现**
服务端使用`shadowsocks-libev 3.2.5` 搭配 `v2ray-plugin v1.3.2`，shadowsocks-libev 的 config.json 配置如下：
```
{
    "server":"::",
    "mode":"tcp_only",
    "server_port":808,
    "local_port":10800,
    "password":"*********",
    "timeout":300,
    "method":"aes-256-gcm",
    "plugin":"/opt/v2ray-plugin_linux_amd64",
    "plugin_opts":"server;tls;host=example.com;cert=/root/.acme.sh/example.com_ecc/example.com.cer;key=/root/.acme.sh/example.com_ecc/example.com.key"
}
```
备注： `example.com` 为替换后的网址，`808`为替换后的端口。

在配置完成后，服务器上的 shadowsocks-libev 可以顺利启动，但是在 nekoray 中，配置后无法连接，返回错误提示：
```
2023/07/29 04:39:24 [Warning] core: Xray 1.8.3 started
2023/07/29 04:39:24 [Info] app/dispatcher: default route for tcp:cp.cloudflare.com:80
2023/07/29 04:39:24 [Info] transport/internet/tcp: dialing TCP to tcp:123.45.67.89:808
2023/07/29 04:39:25 [Info] proxy/shadowsocks: tunneling request to tcp:cp.cloudflare.com:80 via TCP:123.45.67.89:808
[[Shadowsocks] MY_DO_SFO_IPv4] 测试错误: Get "http://cp.cloudflare.com/": EOF
```
备注： `123.45.67.89` 为替换后的IP。

服务端返回以下错误：
```
Jul 29 04:39:24 localhost ss-server[15286]: 2023/07/29 04:39:24 http: TLS handshake error from 123.45.67.89:50094: tls: first record does not look like a TLS handshake
```

以下为 nekoray 的设置截图：
![image](https://github.com/MatsuriDayo/nekoray/assets/515763/f220ddd5-3aa3-419b-8f33-9642bf2dfef6)

相同的配置，使用 ![v2ray-plugin](https://github.com/shadowsocks/v2ray-plugin) 插件的 Shadowsocks for Windows 则可以正常工作：
![image](https://github.com/MatsuriDayo/nekoray/assets/515763/a28b0f2a-8349-4b5f-b5a3-16453af6dcc0)

如果有任何需要补充的地方，请随时提问，感谢。

**Comment by xchacha20-ietf-poly1305** [comment]
更换 sing-box 内核是否有同样的情况？

**Comment by chenshaoju** [comment]
> 更换 sing-box 内核是否有同样的情况？

感谢点拨，切换到 sing-box 内核后提示配置文件相关的错误，删除服务器并重新配置后正常。🙏

![Snipaste_2023-07-29_19-33-15](https://github.com/MatsuriDayo/nekoray/assets/515763/bc21d17d-18b0-41da-9c99-ecc53fa53929)

![Snipaste_2023-07-29_19-35-47](https://github.com/MatsuriDayo/nekoray/assets/515763/73b2415e-58b9-4938-9a01-bbf074fbb2c2)

此 issue 已关闭。
