### ISSUE TITLE
激活节点报错

### ISSUE THREAD

**Issue by zhouxinghong** [MatsuriDayo/nekoray#760]
**描述问题**
激活节点程序弹出以下错误信息
预期行为：

实际行为：

**如何复现**

提供有帮助的截图，录像，文字说明，订阅链接等。
![image](https://github.com/MatsuriDayo/nekoray/assets/54253524/98f7fe4f-278e-4ea3-926e-6e8dfd1ae864)

**日志**

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by zhouxinghong** [comment]
```html
2023/07/25 09:47:01 nekobox_core grpc server listening at 127.0.0.1:19022
2023/07/25 09:52:59 nekobox_core grpc server listening at 127.0.0.1:15080
2023/08/01 02:29:57 nekobox_core grpc server listening at 127.0.0.1:15017
```

**Comment by zhouxinghong** [comment]
版本：3.13与3.14
系统：Win10
3.13版之前没有此问题

**Comment by huangzulin** [comment]
同样问题
