### ISSUE TITLE
go代码编译报错

### ISSUE THREAD

**Issue by bb33bb** [MatsuriDayo/nekoray#796]
**描述问题**
之前编译一直OK，但是这两天最新版编译报错，不知道为何。编译go部分编译失败。

**如何复现**
```
#! /bin/bash
git clone --recurse-submodules https://github.com/MatsuriDayo/nekoray
cd nekoray
./libs/build_deps_all.sh
bash libs/get_source.sh
GOOS=linux GOARCH=amd64 bash libs/build_go.sh
mkdir build
cd build
cmake -GNinja ..
ninja

# go build -tags "with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api"
```

**Comment by xchacha20-ietf-poly1305** [comment]
日志

**Comment by bb33bb** [comment]
package nekoray_core
        imports github.com/xtls/xray-core/main/json
        imports github.com/xtls/xray-core/infra/conf
        imports github.com/xtls/xray-core/proxy/wireguard
        imports gvisor.dev/gvisor/pkg/bufferv2
        imports gvisor.dev/gvisor/pkg/atomicbitops
        imports gvisor.dev/gvisor/pkg/state
        imports gvisor.dev/gvisor/pkg/state/wire
        imports gvisor.dev/gvisor/pkg/gohacks: build constraints exclude all Go files in /home/avboy/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/gohacks

**Comment by bb33bb** [comment]
初步目测是这个没成，其他的都OK，可以编译。

**Comment by bb33bb** [comment]
package github.com/xtls/xray-core/main
        imports github.com/xtls/xray-core/main/distro/all
        imports github.com/xtls/xray-core/main/commands/all
        imports github.com/xtls/xray-core/infra/conf
        imports github.com/xtls/xray-core/proxy/wireguard
        imports gvisor.dev/gvisor/pkg/bufferv2
        imports gvisor.dev/gvisor/pkg/atomicbitops
        imports gvisor.dev/gvisor/pkg/state
        imports gvisor.dev/gvisor/pkg/state/wire
        imports gvisor.dev/gvisor/pkg/gohacks: build constraints exclude all Go files in /home/avboy/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/gohacks


xray和上面相同报错。谢谢前辈援助！

**Comment by bb33bb** [comment]
go: xray-core/proxy/wireguard imports
        gvisor.dev/gvisor/pkg/bufferv2: module gvisor.dev/gvisor@latest found (v0.0.0-20230814211056-6a4a48e6db20), but does not contain package gvisor.dev/gvisor/pkg/bufferv2

**Comment by xchacha20-ietf-poly1305** [comment]
破案：Xray 那边还没适配 go 1.21，因为有着 gVisor、wireguard-go、quic-go 三大屎山。

请使用 go 1.20 编译。

**Comment by bb33bb** [comment]
> 破案：Xray 那边还没适配 go 1.21，因为有着 gVisor、wireguard-go、quic-go 三大屎山。
> 
> 请使用 go 1.20 编译。

谢谢大神！
