### ISSUE TITLE
界面上的 `连接` 中没有任何内容

### ISSUE THREAD

**Issue by Glucy-2** [MatsuriDayo/nekoray#806]
**描述问题**

nekoray 3.17，sing-box 核心和 Xray核心都试过，Debian testing

是功能还没做？

预期行为：

有内容显示

实际行为：

![图片](https://github.com/MatsuriDayo/nekoray/assets/53287753/8963266e-3311-4257-99e4-a863efdf70d8)

**Comment by xchacha20-ietf-poly1305** [comment]
ray: 设置开启连接统计

box: 没有这个功能

**Comment by frank-hank** [comment]
> ray: 设置开启连接统计
> 
> box: 没有这个功能

解答了我一年多的疑问。
