### ISSUE TITLE
配置区宽度自定义

### ISSUE THREAD

**Issue by fangyuan99** [MatsuriDayo/nekoray#822]
**描述建议**
![image](https://github.com/MatsuriDayo/nekoray/assets/62874116/aa7810e1-dc5c-43bb-8d1a-91daeec759bf)

配置区宽度自定义，希望可以类似win文件管理器一样，自定义列的宽度

**建议的必要性**
节点的类型和地址之类的无关紧要的列宽度没必要这么大，后面一些测试结果和流量信息可能会看不到

**Comment by xchacha20-ietf-poly1305** [comment]
分组中开启 手动调节列宽

**Comment by fangyuan99** [comment]
> 分组中开启 手动调节列宽

看到了，要是在文档中加入就好了，设置有点多没找到
