### ISSUE TITLE
编辑分组的前置代理后不弹出子窗口

### ISSUE THREAD

**Issue by cjchome** [MatsuriDayo/nekoray#832]
Windows x64版，进入分组，随便新建或编辑一个分组，在前置代理处点“无”，分组子窗口消失，然后就再也打不开任何子窗口了，只能退出NekoRay再重新运行程序才能恢复正常

**Comment by xchacha20-ietf-poly1305** [comment]
子窗口消失是让你选节点的，按 Esc 退出

**Comment by cjchome** [comment]
> 子窗口消失是让你选节点的，按 Esc 退出

明白了，谢谢~
