### ISSUE TITLE
i need a .rpm package for OpenSUSE

### ISSUE THREAD

**Issue by nullptroma** [MatsuriDayo/nekoray#835]
**描述建议**
i need a .rpm package for OpenSUSE. It is advisable to put the package in the OBS
**建议的必要性**

**Comment by xchacha20-ietf-poly1305** [comment]
https://github.com/xchacha20-ietf-poly1305/nekoray/releases/tag/3.18

I need someone to test (

**Comment by nullptroma** [comment]
I will try and post the results here

**Comment by nullptroma** [comment]
It works! Thx

**Comment by stone-w4tch3r** [comment]
For now this [copr](https://copr.fedorainfracloud.org/coprs/yohane-shiro/nekoray/) is available
