### ISSUE TITLE
开启代理后访问国内网址延迟高

### ISSUE THREAD

**Issue by lfxx** [MatsuriDayo/nekoray#852]
**描述问题**
简易路由选择绕过局域网和大陆时，访问国内网址响应很慢，大概有1-2s的延迟才能刷新出来
预期行为：
访问国内网址响应很快
**如何复现**
代理协议选择naive
简易路由选择绕过局域网和大陆时，访问国内网址

**日志**
[neko.log](https://github.com/MatsuriDayo/nekoray/files/12492173/neko.log)

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by xchacha20-poly1305** [comment]
您可能想启用 DNS 路由或者尝试更换 底层 DNS。

**Comment by lfxx** [comment]
> 您可能想启用 DNS 路由或者尝试更换 底层 DNS。

您好，目前是默认勾选dns路由的。
![Screenshot-20230901112934-770x367](https://github.com/MatsuriDayo/nekoray/assets/27956643/3e2d658c-3c0d-49f8-9d7d-f36c273f7fe6)
您看一下需要怎么测试呢，把localhost的dns换一下吗

**Comment by xchacha20-poly1305** [comment]
基本设置 -> 核心 -> 核心设置 -> 将底层 DNS 改为一个您认为延迟低的

**Comment by lfxx** [comment]
> 基本设置 -> 核心 -> 核心设置 -> 将底层 DNS 改为一个您认为延迟低的

好的谢谢
