### ISSUE TITLE
tiktok无法访问问题

### ISSUE THREAD

**Issue by Everlasting16108** [MatsuriDayo/nekoray#854]
**描述问题**

预期行为：通过简单路由代理tiktok上网

实际行为：跳转为tiktok官方dns服务器导致无法访问
**如何复现**
![QQ截图20230901141527](https://github.com/MatsuriDayo/nekoray/assets/67988137/6493663c-2cf3-4674-9a81-f7080b4ac1a7)

提供有帮助的截图，录像，文字说明，订阅链接等。
**日志**
INFO[0059] [340285054 0ms] inbound/mixed[mixed-in]: inbound connection to www.tiktok.com:443
INFO[0059] [340285054 0ms] outbound/direct[bypass]: outbound connection to www.tiktok.com:443
INFO[0059] dns: exchanged s20.tiktokcdn.com CNAME s20.tiktokcdn.com. 1 IN CNAME s20.tiktokcdn.com.edgesuite.net.
INFO[0059] dns: exchanged s20.tiktokcdn.com CNAME s20.tiktokcdn.com.edgesuite.net. 1 IN CNAME a1904.mm2.akamai.net.
INFO[0059] dns: exchanged s20.tiktokcdn.com CNAME a1904.mm2.akamai.net. 1 IN CNAME a1904.mm2.akamai.net.0.1.cn.akamaitech.net.
INFO[0059] dns: exchanged s20.tiktokcdn.com A a1904.mm2.akamai.net.0.1.cn.akamaitech.net. 1 IN A 2.19.98.26
INFO[0059] dns: exchanged s20.tiktokcdn.com A a1904.mm2.akamai.net.0.1.cn.akamaitech.net. 1 IN A 2.19.98.49
INFO[0059] dns: exchanged s20.tiktokcdn.com OPT OPT PSEUDOSECTION: EDNS: version 0 flags: MBZ: 0x0001, udp: 4096
INFO[0059] dns: exchanged lf16-tiktok-common.ibytedtos.com CNAME lf16-tiktok-common.ibytedtos.com. 1 IN CNAME lf16-tiktok-common.ibytedtos.com.edgesuite.net.
INFO[0059] dns: exchanged lf16-tiktok-common.ibytedtos.com CNAME lf16-tiktok-common.ibytedtos.com.edgesuite.net. 1 IN CNAME a606.b.akamai.net.
INFO[0059] dns: exchanged lf16-tiktok-common.ibytedtos.com A a606.b.akamai.net. 1 IN A 61.213.189.203
INFO[0059] dns: exchanged lf16-tiktok-common.ibytedtos.com A a606.b.akamai.net. 1 IN A 61.213.189.201
INFO[0059] dns: exchanged lf16-tiktok-common.ibytedtos.com OPT OPT PSEUDOSECTION: EDNS: version 0 flags: MBZ: 0x0001, udp: 4096
INFO[0059] dns: exchanged s20.tiktokcdn.com CNAME s20.tiktokcdn.com. 59 IN CNAME s20.tiktokcdn.com.edgesuite.net.
INFO[0059] dns: exchanged s20.tiktokcdn.com CNAME s20.tiktokcdn.com.edgesuite.net. 59 IN CNAME a1904.mm2.akamai.net.
INFO[0059] dns: exchanged s20.tiktokcdn.com SOA mm2.akamai.net. 59 IN SOA n0mm2.akamai.net. hostmaster.akamai.com. 1693548980 1000 1000 1000 1800
INFO[0059] dns: exchanged s20.tiktokcdn.com OPT OPT PSEUDOSECTION: EDNS: version 0 flags: MBZ: 0x003b, udp: 4096
INFO[0059] dns: exchanged lf16-tiktok-common.ibytedtos.com CNAME lf16-tiktok-common.ibytedtos.com. 600 IN CNAME lf16-tiktok-common.ibytedtos.com.edgesuite.net.
INFO[0059] dns: exchanged lf16-tiktok-common.ibytedtos.com CNAME lf16-tiktok-common.ibytedtos.com.edgesuite.net. 600 IN CNAME a606.b.akamai.net.
INFO[0059] dns: exchanged lf16-tiktok-common.ibytedtos.com SOA b.akamai.net. 600 IN SOA n0b.akamai.net. hostmaster.akamai.com. 1693548981 1000 1000 1000 1800
INFO[0059] dns: exchanged lf16-tiktok-common.ibytedtos.com OPT OPT PSEUDOSECTION: EDNS: version 0 flags: MBZ: 0x0258, udp: 4096
INFO[0059] [2887448455 0ms] inbound/mixed[mixed-in]: inbound connection to s20.tiktokcdn.com:443
INFO[0059] [2887448455 0ms] outbound/direct[bypass]: outbound connection to s20.tiktokcdn.com:443
INFO[0059] dns: exchanged s20.tiktokcdn.com CNAME s20.tiktokcdn.com. 30 IN CNAME s20.tiktokcdn.com.edgesuite.net.
INFO[0059] dns: exchanged s20.tiktokcdn.com CNAME s20.tiktokcdn.com.edgesuite.net. 30 IN CNAME a1904.mm2.akamai.net.
INFO[0059] dns: exchanged s20.tiktokcdn.com A a1904.mm2.akamai.net. 30 IN A 2.19.98.49
INFO[0059] dns: exchanged s20.tiktokcdn.com A a1904.mm2.akamai.net. 30 IN A 2.19.98.26
INFO[0059] dns: exchanged s20.tiktokcdn.com OPT OPT PSEUDOSECTION: EDNS: version 0 flags: MBZ: 0x001e, udp: 4096
INFO[0064] [3450498950 0ms] inbound/mixed[mixed-in]: inbound connection to www.tiktok.com:443
如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by xchacha20-poly1305** [comment]
`geosite:tiktok`

**Comment by Everlasting16108** [comment]
没想到能这么快解决问题，昨天晚上弄了几个小时，感谢您的帮助，谢谢！
![QQ截图20230901142529](https://github.com/MatsuriDayo/nekoray/assets/67988137/cea77332-29d0-49e9-bc59-80356d9a799a)

**Comment by Everlasting16108** [comment]
已完美解决。
