### ISSUE TITLE
BUG: start service: initialize inbound/mixed[mixed-in]: listen tcp 127.0.0.1:2080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by amir1387aht** [MatsuriDayo/nekoray#886]
## 描述问题

预期行为：connect to sub group slot

实际行为：give this error : start service: initialize inbound/mixed[mixed-in]: listen tcp 127.0.0.1:2080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

some explation : I was using the program when for some reason my computer turned off, after turning on the computer, when I try to connect to a link, I received the error you saw above.

**Comment by xchacha20-poly1305** [comment]
Restart nekoray

**Comment by mater1** [comment]
Restart nekoray didnt work

**Comment by HPSDf** [comment]
same problem,do you solve that?

**Comment by amir1387aht** [comment]
> same problem,do you solve that?

yes, reinstall nekoray and restart your pc, but there is no static way to fix

**Comment by MrFMRka** [comment]
I solved the problem without reinstalling Nekoray this way - I changed the SOCKS port from 1080 to 2080. If I go back, the error repeats.
Maybe it'll help someone.

**Comment by amir1387aht** [comment]
> I solved the problem without reinstalling Nekoray this way - I changed the SOCKS port from 1080 to 2080. If I go back, the error repeats. Maybe it'll help someone.

thx

**Comment by hutufeng** [comment]
我也出现了这样的提示，折腾半天是进程里有nekobox_core.exe，我结束进程就ok了，可能是以为退出nekoray，但内核进程还在，而且占用了端口

**Comment by badestgod** [comment]
changed the SOCKS port from 2080 to 1080

**Comment by miladtahanian** [comment]
Just run these commands in windows then it'll fix:

**net stop hns
net start hns**

**Comment by oolott** [comment]
> Just run these commands in windows then it'll fix:
> 
> **net stop hns** 
> **net start hns**

this work on me

**Comment by buchannn** [comment]
> Just run these commands in windows then it'll fix:
> 
> **net stop hns net start hns**

working for me

**Comment by Ivanich69** [comment]
> Just run these commands in windows then it'll fix:
> 
> **net stop hns net start hns**

лучший бро
