### ISSUE TITLE
请问下可否增加一个自启后自动连接上次节点

### ISSUE THREAD

**Issue by zhucaidan** [MatsuriDayo/nekoray#887]
## 描述建议
请问下可否增加一个自启后自动连接上次节点，或者连接自选节点
## 建议的必要性
因为开机自启后有下载软件等依赖socks5代理功能，但是启动后nekoray不会自动连接上次节点需要手动启用才可以连接
可否增加一个启动后自动连接最后一个节点或者选中节点功能？

**Comment by wenliyang** [comment]
程序 - 记住最后的配置，勾选

**Comment by zhucaidan** [comment]
> 程序 - 记住最后的配置，勾选

感谢老铁
