### ISSUE TITLE
nekoray 如何开启udp转发

### ISSUE THREAD

**Issue by cancanneednews** [MatsuriDayo/nekoray#889]
## 描述建议
机场开启了udp转发 用cfw 延迟低， 今天想试试nekoray 发现 好像默认的情况下和clash打游戏延迟不一样
所以我想请问 请问nekoray 有udp转发这个功能吗？还是说要手动写json配置

![图片](https://github.com/MatsuriDayo/nekoray/assets/134935370/2e5c9a3c-575f-4edf-a4b5-a9f7d4bfa418)

![图片](https://github.com/MatsuriDayo/nekoray/assets/134935370/5a5f5f49-6f2e-4cd7-a40e-b447a5c3bc1d)

## 建议的必要性
udp低延迟

**Comment by xchacha20-poly1305** [comment]
默认就开了 udp
