### ISSUE TITLE
BUG: 添加naive协议时提示没有naive核心

### ISSUE THREAD

**Issue by lifei6671** [MatsuriDayo/nekoray#893]
## 描述问题

**预期行为：**

naive协议sing-box是支持的，理论上可以直接使用sing-box来支持naiveproxy。

**实际行为：**

添加naive代理时会提示没有naive核心。

<img width="245" alt="image" src="https://github.com/MatsuriDayo/nekoray/assets/3665700/9d7fa7ae-d99b-48b9-a1c9-fd4ce2d9a46a">

**Comment by xchacha20-poly1305** [comment]
https://sing-box.sagernet.org/zh/faq/#naive

使用 naive 而不想使用它的网络栈是一种既要又要的行为

**Comment by lifei6671** [comment]
> https://sing-box.sagernet.org/zh/faq/#naive
> 
> 使用 naive 而不想使用它的网络栈是一种既要又要的行为

既然做的是sing-box客户端UI，sing-box又没有自己的协议且，sing-box也支持navie。为什么说是既要又要的行为？
