### ISSUE TITLE
希望NekoRay For Windows增加自动更新路由资源(Geo)的功能

### ISSUE THREAD

**Issue by btaskel** [MatsuriDayo/nekoray#894]
## 描述建议
希望NekoRay For Windows增加自动更新路由资源(Geo)的功能
## 建议的必要性
每次更新路由资源都是从V2rayN客户端那边下载的,有点不太方便,如果NekoRay能加上就完美了

**Comment by xchacha20-poly1305** [comment]
https://matsuridayo.github.io/n-configuration/#_7

**Comment by CatSamaDD** [comment]
其实我也觉得是不是可以再考虑下加入这个功能，不是杠，纯建议，如果真的没有此计划的话就当我没说吧。
Android版不是就有这个更新和geo源选择的功能嘛。
开发者大佬们可能连GUI都不需要，用命令行还省内存。
但是GUI的话windows单独搞个计划任务啥的更新geo感觉还是有点不太方便，而且对不懂得这块的人也不太友好。
