### ISSUE TITLE
BUG: ICMP流量无法代理

### ISSUE THREAD

**Issue by do02fw** [MatsuriDayo/nekoray#900]
## 描述问题

预期行为：
ICMP流量可以代理
实际行为：
ICMP流量没有代理。ping返回结果1ms
## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。
开启TUN模式，服务端是Hy2，服务端已经开启UDP（YouTube显示是http3协议），但是ICMP流量无法代理，ping返回1ms，请问应该如何让它代理ICMP流量

客户端设置为
tun设置
stack gvisor mtu 9000 启用v6tun  内部tun 隐藏控制台

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by do02fw** [comment]
还有一个问题，DNS泄露
![1](https://github.com/MatsuriDayo/nekoray/assets/138294823/3f8275ac-310f-4777-8c5e-1fa8c03feebc)

**Comment by xchacha20-poly1305** [comment]
目前大部分翻墙协议都只支持代理 Layer3 流量，自然无法代理 icmp。如果您使用 Linux，则 icmp 不会被 Tun 劫持，而是返回真实的结果；而 windows 则无望了。

**Comment by do02fw** [comment]
> nekoray 3.17 windows 10 22h2在TUN模式下防止DNS泄露的设置，在ipv4环境下实际使用结果，如果使用ipv6（即启用Tun IPv6勾选），那么需要你自己实际测试组合的勾选项，stack gvisor mtu 9000一样的
> 
> sing-box内核情况下 Strick Route必须勾选 FakDNS必须勾选 内部TUN无所谓
> 
> xray内核情况下 Strick Route必须勾选 FakDNS不能勾选
> 
> 如果使用其他nekoray版本，或其他操作系统版本，需要你自己实际测试组合的勾选项

这样设置确实不泄露了，但是会报错，微软的outlook的exchange报错，
![2](https://github.com/MatsuriDayo/nekoray/assets/138294823/1ee00568-5c80-41b6-a14b-34e397db359c)

**Comment by do02fw** [comment]
服务器配置文件
![8](https://github.com/MatsuriDayo/nekoray/assets/138294823/4a686e74-2ab7-4ee5-abc8-aa06609d1b3b)

**Comment by do02fw** [comment]
真的服了，刚刚说完，结果打开pixiv发现图片全部加载失败。测速一切正常
![2](https://github.com/MatsuriDayo/nekoray/assets/138294823/b81d6b6e-9047-4974-8964-f8d79e70e0d3)

**Comment by do02fw** [comment]
测速是280Mbps。Xtom的香港

**Comment by do02fw** [comment]
> > nekoray 3.17 windows 10 22h2在TUN模式下防止DNS泄露的设置，在ipv4环境下实际使用结果，如果使用ipv6（即启用Tun IPv6勾选），那么需要你自己实际测试组合的勾选项，stack gvisor mtu 9000一样的
> > sing-box内核情况下 Strick Route必须勾选 FakDNS必须勾选 内部TUN无所谓
> > xray内核情况下 Strick Route必须勾选 FakDNS不能勾选
> > 如果使用其他nekoray版本，或其他操作系统版本，需要你自己实际测试组合的勾选项
> 
> 这样设置确实不泄露了，但是会报错，微软的outlook的exchange报错， ![5](https://user-images.githubusercontent.com/138294823/270833921-0025f600-3bfa-4722-a3a3-0564294c5380.png) ![6](https://user-images.githubusercontent.com/138294823/270833931-19606b3f-e80c-44eb-96af-5a87f62a67f4.png) ![2](https://user-images.githubusercontent.com/138294823/270833318-1ee00568-5c80-41b6-a14b-34e397db359c.png) ![3](https://user-images.githubusercontent.com/138294823/270833543-ae324fbd-a919-4797-92b8-522ad0ffaf45.png) @egg1234 @arm64v8a @chika0801 我有强迫症，容不下一个错误，请问有没有什么解决办法

取消内部TUN后不报错了，真的是服了，BUG好多

**Comment by do02fw** [comment]
但取消内部TUN后会导致新的BUG出现，电脑右下角会显示无网络的图标，实际上网络是正常的
![3](https://github.com/MatsuriDayo/nekoray/assets/138294823/4aab5ab7-228f-4d37-891c-84b4a92dee0e)
我希望能像wireguard那样的网卡tun模式，这样就不会有那么多BUG了，请帮我告诉singbox的作者

**Comment by do02fw** [comment]
又有新的BUG了，访问一些网站会提示证书不安全
![3](https://github.com/MatsuriDayo/nekoray/assets/138294823/d154bff1-e3f3-49f7-9348-047b1fc5dbb4)

**Comment by do02fw** [comment]
我服了，我先不用这个了

**Comment by l619534951** [comment]
有病
