### ISSUE TITLE
如何查看提交给core的最终config

### ISSUE THREAD

**Issue by CXwudi** [MatsuriDayo/nekoray#902]
## 描述建议

平时都是用命令行启动sing-box客户端, 这次转到nekoray虽然成功, 但想确定一下nekoray配出来的配置跟我自己手写的sing-box JSON文件配置有多大差别

## 建议的必要性

Clash For Windows就有这样的功能:
![image](https://github.com/MatsuriDayo/nekoray/assets/17377423/7702faf8-4915-436c-96ac-70e6f5d397fa)
希望nekoray也有这样的功能

**Comment by CXwudi** [comment]
查到了，感谢方法

formatting好弄，vs code就能搞

不过我想查最终config的原因是因为我发现nekoray连接我的sing-box服务器都是发送的IP而不是域名，导致我服务器那边如果不开sniff把IP变回域名，根本做不了geosite相关的routing。而我用命令行连接我服务端的时候就没有问题（fakeip下客户端发送域名而不是IP）

可惜看了最终config依旧不知道为什么nekoray会用IP连接🤔

**Comment by CXwudi** [comment]
关闭issue了，毕竟知道了怎么导出最终config了

**Comment by xchacha20-poly1305** [comment]
> 不过我想查最终config的原因是因为我发现nekoray连接我的sing-box服务器都是发送的IP而不是域名，导致我服务器那边如果不开sniff把IP变回域名，根本做不了geosite相关的routing。而我用命令行连接我服务端的时候就没有问题（fakeip下客户端发送域名而不是IP）
> 
> 可惜看了最终config依旧不知道为什么nekoray会用IP连接🤔

https://github.com/SagerNet/sing-box/blob/61ac141124a6c8c09a35ba70a14b5587371cf5e7/route/router.go#L660-L664

开了 sniffing over ride 才会发域名哦。

**Comment by CXwudi** [comment]
> > 不过我想查最终config的原因是因为我发现nekoray连接我的sing-box服务器都是发送的IP而不是域名，导致我服务器那边如果不开sniff把IP变回域名，根本做不了geosite相关的routing。而我用命令行连接我服务端的时候就没有问题（fakeip下客户端发送域名而不是IP）
> > 可惜看了最终config依旧不知道为什么nekoray会用IP连接🤔
> 
> https://github.com/SagerNet/sing-box/blob/61ac141124a6c8c09a35ba70a14b5587371cf5e7/route/router.go#L660-L664
> 
> 开了 sniffing over ride 才会发域名哦。

问题是为什么我的命令行客户端启动就没问题

我打算新创建个issue单独讨论这个问题，也会把nekoray和我自己手搓的命令行客户端配置发出来

**Comment by xchacha20-poly1305** [comment]
FakeID 自然是发域名，请确保配置完全一致
