### ISSUE TITLE
BUG: 无法使用geoip:!cn实现仅代理海外IP

### ISSUE THREAD

**Issue by drsanwujiang** [MatsuriDayo/nekoray#907]
## 描述问题

预期行为：域名策略IPIfNotMatch，简易路由默认出站bypass，将geoip:!cn填入代理，实现仅代理海外IP

实际行为：访问YouTube、Google等网站被路由为bypass

**Comment by xchacha20-poly1305** [comment]
可能是 DNS 出站问题？试试把 DNS 出站改成代理

**Comment by Nyar233** [comment]
可能是因为路由里有个根据端口匹配的兜底规则，导致 IPIfNotMatch 实际上并没有起作用

**Comment by heibailiangxiangwang20** [comment]
我前两天也遇到这个问题，经过各种查询，好像是sing-box不支持反向代理（就是!**），xray可以，所以你是不是选择了singbox核心

**Comment by drsanwujiang** [comment]
> 我前两天也遇到这个问题，经过各种查询，好像是sing-box不支持反向代理（就是!**），xray可以，所以你是不是选择了singbox核心

使用的是Xray

> 可能是 DNS 出站问题？试试把 DNS 出站改成代理

默认就是proxy

**Comment by Nyar233** [comment]
> > 我前两天也遇到这个问题，经过各种查询，好像是sing-box不支持反向代理（就是!**），xray可以，所以你是不是选择了singbox核心
> 
> 使用的是Xray
> 
> > 可能是 DNS 出站问题？试试把 DNS 出站改成代理
> 
> 默认就是proxy

你把完整配置导出看看就知道了，router 里有个 port 匹配规则，这个规则会匹配所有的流量，所以即使是前面没有匹配到的域名，也不会被解析成 ip 再执行第二次匹配。要么 nekoray 修改一下这个内置的规则，要么你改用 IPOnDemand

**Comment by drsanwujiang** [comment]
> > > 我前两天也遇到这个问题，经过各种查询，好像是sing-box不支持反向代理（就是!**），xray可以，所以你是不是选择了singbox核心
> > 
> > 
> > 使用的是Xray
> > > 可能是 DNS 出站问题？试试把 DNS 出站改成代理
> > 
> > 
> > 默认就是proxy
> 
> 你把完整配置导出看看就知道了，router 里有个 port 匹配规则，这个规则会匹配所有的流量，所以即使是前面没有匹配到的域名，也不会被解析成 ip 再执行第二次匹配。看样子你的规则里只有geoip:!cn，因为域名不会解析成ip再匹配，所以Youtube 等流量会直接命中端口规则，导致全部都走了bypass。
> 
> `{ "outboundTag": "proxy", "port": "0-65535", "type": "field" }` `{ "outboundTag": "bypass", "port": "0-65535", "type": "field" }`
> 
> 所以要么 nekoray 修改一下这个内置的规则，要么你改用 IPOnDemand，当然你还可以选择在路由里添加域名规则。

IPOnDemand 目前看来可以，十分感谢
