### ISSUE TITLE
dns: exchange failed tuic

### ISSUE THREAD

**Issue by Evolve6996** [MatsuriDayo/nekoray#917]
hello, iam running Tuic and have this error it happens for many domains not only YouTube, i also changed remote dns but it didnt fix

![Untitled](https://github.com/MatsuriDayo/nekoray/assets/91710620/903d57ab-fce4-464c-b314-8eb4734db4d7)

thanks for your help ❤️ 

ERROR[0058] dns: exchange failed for www.youtube.com. IN AAAA: Post "https://1.0.0.1/dns-query": context canceled
ERROR[0057] dns: exchange failed for www.youtube.com. IN A: Post "https://1.0.0.1/dns-query": context deadline exceeded

**Comment by ash27kan** [comment]
Any update about this error? I have the same one. I had Ubuntu and everything was fine until I changed my distro to the Pop os and this error occurred.

**Comment by Maxim-Root** [comment]
Hello, I was able to solve the problem by uninstalling the program and downloading it again apparently the constant change of program settings caused a kernel bug or something like that
