### ISSUE TITLE
BUG: nekoray 警告 “RunGuard disallow to run, use -many to force start”，无论我是否真的开启了多个 nekoray 实例

### ISSUE THREAD

**Issue by EarthMessenger** [MatsuriDayo/nekoray#955]
## 描述问题

预期行为：

在没有 nekoray 实例运行的时候，运行 nekoray 能直接开启新的 nekoray 实例。

实际行为：

警告说 “RunGuard disallow to run, use -many to force start”，必须要带 `-many` 参数才能启动。

## 如何复现

直接运行 nekoray。

![RunGuard warns even when there isn't any nekoray instance](https://github.com/MatsuriDayo/nekoray/assets/49364506/d88ac436-298b-4218-a477-4ee281fc9d49)

系统：Arch Linux
内核：6.1.57-1-lts
nekoray 版本：3.22
Qt 版本：6.6.0

## 日志

没有日志。

**Comment by ThatcherChen** [comment]
我使用的是archlinuxcn的nekoray-git包，有同样的问题

**Comment by ludenticus** [comment]
Provisional solution:

Modify `/usr/share/applications/nekoray.desktop`:

```sh
/usr/bin/nekoray -many
```

**Comment by uzvg** [comment]
I meet this warning too.

**Comment by uzvg** [comment]
I met this warning too.
![Screenshot from 2023-10-15 00-02-00](https://github.com/MatsuriDayo/nekoray/assets/32935216/047b4377-bb41-4c93-9818-ba0eb79d70e7)

**Comment by lonble** [comment]
3.24这个bug还在

**Comment by yibajianghudao** [comment]
RunGuard disallow to run, use -many to force start.

这个提示再次出现在我的电脑上，我配置了nekoray开机启动，当我进入桌面后，nekoray已经正常打开，并出现了该提示，功能可以正常使用，但是我无法再次关闭后重新打开，会直接弹出该提示，无法打开。

**Comment by HowardZorn** [comment]
This problem may not be fixed in 32ef100.

I have the same prompt box on my Arch Linux (6.6.1-arch1-1) and the nekoray version in pacman is 3.24-2.

**Comment by EarthMessenger** [comment]
3.24 is published before that commit, so RunGuard on that version is not working. 
 
Now I update to 3.25 and the problem is fixed. Thanks to the contributors.
