### ISSUE TITLE
设置系统代理时设置为监听地址+端口而不是127.0.0.1+{port}

### ISSUE THREAD

**Issue by fs8vsx59h** [MatsuriDayo/nekoray#964]
## 描述建议

为了让局域网内设备使用nekoray的socks5我将nekoray的监听地址设置为192.168.1.6，设置完系统代理发现浏览器报“未连接到代理服务器”，检查系统设置后发现nekoray将系统代理设置为127.0.0.1:2080。希望将系统代理设置为监听地址+端口而不是固定的127.0.0.1+{port}。

## 建议的必要性

在想要让局域网设备连接而不监听0.0.0.0时该功能可以避免手动修改系统代理的麻烦。

**Comment by lgdsgd2000** [comment]
勾选“允许其他设备连接”，该选项会监听0.0.0.0

**Comment by ZYGLQexplorer** [comment]
监听地址改为 `0.0.0.0` ，不要用内网IP地址

**Comment by zslqhua** [comment]
俺是个老白，就是年纪大而网络姿势又贫瘠。想在这里搭船请教个问题：就是如何在chrome中的插件switchyomega 中配置nekoray? http 127.0.0.1 后面的代理端口是多少？2080 不对，始终不能出墙。同样的节点，clash可以出墙的。实在不知道问题出在哪里了！有劳各位大佬了！
