### ISSUE TITLE
BUG: 开启tun模式后任务栏WiFi图标不会变成以太网图标

### ISSUE THREAD

**Issue by fzs209** [MatsuriDayo/nekoray#967]
## 描述问题
开启tun模式后任务栏WiFi图标不会变成以太网图标

开启tun模式后
![image](https://github.com/MatsuriDayo/nekoray/assets/75153914/560d1543-fbdd-4c2a-8dfd-a837b153963d)
不会变为
![image](https://github.com/MatsuriDayo/nekoray/assets/75153914/c89558e7-a385-4af9-b758-488925fe189f)

下面是设置
![image](https://github.com/MatsuriDayo/nekoray/assets/75153914/541c84d4-f37f-4ae9-b7d2-4193ba9f2941)
![image](https://github.com/MatsuriDayo/nekoray/assets/75153914/15b5e61f-5227-4815-8447-52070670aa69)
![image](https://github.com/MatsuriDayo/nekoray/assets/75153914/d24267e0-2f50-4ed4-833b-ac506e62716d)

请问要如何解决

**Comment by Misaka-blog** [comment]
正常情况，能用就行

你就看有没有 nekoray-tun 这个适配器即可，如下图为正常使用情况

![image](https://github.com/MatsuriDayo/nekoray/assets/122191366/9041ca44-9b3f-4100-8a53-d28aaac0335c)
