### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by mohammadtagi** [MatsuriDayo/nekoray#974]
Hi 
when i try to lunch the app it does'nt word and show me this error:

![photo_2023-10-21_17-29-00](https://github.com/MatsuriDayo/nekoray/assets/148634516/ed39d1f3-aa7f-4a5b-a1ad-0d619a7557fd)

how can i solve this? 

please help me

**Comment by HosseinKoofi** [comment]
Hi, 
The source of the problem can be a few things,
You may follow this [guideline](https://softwarekeep.com/help-center/repair-the-procedure-entry-point-could-not-be-located-error-in-windows-10) to fix the error.

**Comment by Dystnine** [comment]
That's normal, since this software is longer support windows 7/8 now.

**Comment by Misaka-blog** [comment]
Upgrade to Windows 10 or later, it's not longer for supports older version of Windows
