### ISSUE TITLE
BUG: 找不到hysteria核心，請前往設置

### ISSUE THREAD

**Issue by ghost** [MatsuriDayo/nekoray#976]
## 描述问题

预期行为：正常測速

实际行为：找不到hysteria核心，請前往設置

## 如何复现

hysteria://155.94.235.182:55479/?insecure=1&peer=wechat.com&upmbps=1126&downmbps=1126&alpn=h3&obfs=xplus&obfsParam=yJbnicVt9fMHLbd7yVS3vb3UTNDTnROxCJH2gAMHv2PkWSN8nG&protocol=wechat-video#Hys-USA2

hysteria://204.44.109.33:42081/?insecure=1&peer=wechat.com&upmbps=1126&downmbps=1126&alpn=h3&obfs=xplus&obfsParam=VOwHitqv92F62xYpVliiLTDhntsOqoN5moEVgJ9nEaPACiThYk&protocol=wechat-video#Hys-USA3

複製后右鍵點擊當前選中，點擊Url Test

提供有帮助的截图，录像，文字说明，订阅链接等。
<img width="587" alt="nekoray_8UPSlx5S1k" src="https://github.com/MatsuriDayo/nekoray/assets/65935235/6c5c606c-443d-43bb-9aae-c274d3fa3a36">

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by HeinousAgenda38** [comment]
![image](https://github.com/MatsuriDayo/nekoray/assets/60530947/95f76908-5885-4161-bf24-1cec55e290bc)

[hysteria1 核心下载](https://github.com/apernet/hysteria/releases/tag/v1.3.5)
