### ISSUE TITLE
BUG: 分享链接导入配置出错

### ISSUE THREAD

**Issue by FanLuoh** [MatsuriDayo/nekoray#981]
## 描述问题

预期行为：导入vmess+tcp的新分享链接格式时正常导入

实际行为：导入vmess+tcp的新分享链接格式时导入的配置是vmess+tcp+tls的

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

基本设置中关闭“旧分享链接格式*”
手动添加一个vmess+tcp的配置
选中添加的节点右键分享显示分享链接并复制
导入复制的url，例子如下
vmess://00000000-0000-0000-0000-000000000000@1.2.3.4:12345?encryption=auto&security=&fp=chrome&type=tcp#test
实际导入的是
vmess://00000000-0000-0000-0000-000000000000@1.2.3.4:12345?encryption=auto&security=tls&fp=chrome&type=tcp#test

旧分享链接格式正常

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

3.42最新版本

**Comment by FanLuoh** [comment]
直接导入
vmess://00000000-0000-0000-0000-000000000000@1.2.3.4:12345?type=tcp#test
也会生成一个vmess+tcp+tls的配置

**Comment by Misaka-blog** [comment]
这个协议风控性挺高，自己修改下用用就行，不太想修
