### ISSUE TITLE
BUG: the produce entry point systemparametersInfoForDpi could not be located in the dynamic link library (windows 8.1, 7)

### ISSUE THREAD

**Issue by H-Khoujani** [MatsuriDayo/nekoray#983]
## Describe the problem

I downloaded the last version of nekoray from github and when I double click to main exe file it throw this message
I also installed MSVC 2019 & Microsoft Visual c++ Redistributation 2015-2022

![Capture](https://github.com/MatsuriDayo/nekoray/assets/72504271/d41c0390-818d-4949-9628-aea72643abac)

**Comment by Misaka-blog** [comment]
Upgrade to Windows 10 or later, thx
