### ISSUE TITLE
IN A: Post "https://8.8.8.8/dns-query": read tcp XX.XX.XX.XX:XXXX->XX.XX.XX.XX:XXXX: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by melzyy** [MatsuriDayo/nekoray#984]
## Describe the problem

Expected behavior: dns resolving works

Actual behavior: ERROR[0002] dns: exchange failed for mtalk.google.com. IN A: Post "https://8.8.8.8/dns-query": read tcp 192.168.1.37:54705->XX.XX.XX.XX:43301: wsarecv: An existing connection was forcibly closed by the remote host. for every dns request

## How to reproduce
i dont know, it doesnt work only on my windows pc, works fine on windows for my friends that use the same server and also works fine on my phone through nekobox on the same network

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

![image](https://github.com/MatsuriDayo/nekoray/assets/71926357/7fc8b8d8-5602-4171-a5c9-537d1329d76e)

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by melzyy** [comment]
fixed itself somehow lol

**Comment by leic4u** [comment]
could you please tell us how do you fix it, thanks bro.

**Comment by melzyy** [comment]
> could you please tell us how do you fix it, thanks bro.

no idea, it randomly appeared again, struggling with it rn

**Comment by leic4u** [comment]
> > could you please tell us how do you fix it, thanks bro.
> 
> no idea, it randomly appeared again, struggling with it rn

It seems that IP was blocked in TCP by my ISP.

**Comment by melzyy** [comment]
> > > could you please tell us how do you fix it, thanks bro.
> > 
> > 
> > no idea, it randomly appeared again, struggling with it rn
> 
> It seems that IP was blocked in TCP by my ISP.

try changing your encryption method and port

for some reason only my windows pc had this issue with dns requests (no issues from my phone with the same settings), i changed my encryption method on the server and it works now lol, last time it fixed itself
