### ISSUE TITLE
feture: wireguard 如何同时支持两组server

### ISSUE THREAD

**Issue by kpddadyo72419** [MatsuriDayo/nekoray#986]
## 描述问题

预期行为：希望一个配置同时支持两个IP,根据IPv6+v4自动分流

实际行为：如图，貌似只能写一组

![image](https://github.com/MatsuriDayo/nekoray/assets/132160684/36533bb5-8058-4aa3-8776-32029b3dd18b)

**Comment by Misaka-blog** [comment]
做梦去，只能支持一个

**Comment by kpddadyo72419** [comment]
> 做梦去，只能支持一个

tun模式不是模拟网卡么，网卡不是应该支持配置多个IP么
