### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by Ma5t3rful** [MatsuriDayo/nekoray#994]
## Description suggestions
It would be great if we have a snap version of this software.

**Comment by SaltedFishesNG** [comment]
You can build nekoray yourself.
Actually, nekoray has a Pre-release version, it's just the frequency of updates ........

**Comment by Master811129** [comment]
Yes, But for many users that use snaps. Its way more convenient to just install this app as a snap package. Plus people would see it in [Snap Store](https://snapcraft.io/store/) and notice that the project itself exists. It helps with the popularity of the project.

**Comment by Master811129** [comment]
Any plan? @arm64v8a
